dic = {
    # 属性 大小写
    'Fire': '火焰',
    'Lightning': '闪电',
    'Ice': '寒冰',
    'Nature': '自然',
    'Arcane': '奥术',
    'Dark': '黑暗',
    'Holy': '神圣',
    'Sorcery': '法术',
    'Conjuration': '召唤',
    'Enchantment': '附魔',
    'Word': '真言',
    'Orb': '法球',
    'Dragon': '巨龙',
    'Translocation': '移位',
    'Metallic': '金属',
    'Eye': '视线',
    'Chaos': '混沌',
    'fire': '火焰',
    'lightning': '闪电',
    'ice': '寒冰',
    'nature': '自然',
    'arcane': '奥术',
    'dark': '黑暗',
    'holy': '神圣',
    'sorcery': '法术',
    'conjuration': '召唤',
    'enchantment': '附魔',
    'word': '真言',
    'orb': '法球',
    'dragon': '巨龙',
    'translocation': '移位',
    'metallic': '金属',
    'eye': '视线',
    'chaos': '混沌',
    # 其他 大小写
    'Damage': '伤害',
    'damage': '伤害',
    'Heal': '治疗',
    'heal': '治疗',
    'Damage type': '伤害类型',
    'damage type': '伤害类型',
    'Max Charges': '充能上限',
    'max charges': '充能上限',
    'Radius': '半径',
    'radius': '半径',
    'Poison': '毒性',
    'poison': '毒性',
    'Range': '射程',
    'Melee': '近战',
    'Physical': '物理',
    'physical': '物理',
    'Poisoned': '中毒',
    'poisoned': '中毒',
    'Stun': '击晕',
    'stun': '击晕',
    'Petrified': '石化',
    'petrified': '石化',
    'Glassified': '冻结',
    'glassified': '冻结',
    'Frozen': '冻结',
    'frozen': '冻结',
    'Berserk': '狂暴',
    'berserk': '狂暴',
    'Blind': '致盲',
    'blind': '致盲',
    'Stunned': '击晕',
    'stunned': '击晕',
    'Living': '活物',
    'living': '活物',
    'Flying': '飞行',
    'flying': '飞行',
    'Construct': '造物',
    'construct': '造物',
    'Undead': '不死',
    'undead': '不死',
    'Demon': '恶魔',
    'demon': '恶魔',
    'petrify': '石化',
    '': '',
    '': '',
    '': '',
    '': '',


    # 玩家咒语
    'Death Bolt': '死亡之箭',
    'Fireball': '火球术',
    'Icicle': '冰锥术',
    'Lightning Bolt': '闪电箭',
    'Poison Sting': '毒刺术',
    'Magic Missile': '魔法飞弹',
    'Wolf': '召狼术',
    'Annihilate': '歼灭术',
    'Blazerip': '熔刃术',
    'Boiling Blood': '热血术',
    'Chain Lightning': '闪电链',
    'Chaos Barrage': '混沌箭雨',
    'Disperse': '驱散术',
    'Eye of Fire': '火焰之眼',
    'Eye of Ice': '寒冰之眼',
    'Eye of Lightning': '闪电之眼',
    'Eye of Rage': '愤怒之眼',
    'Fan of Flames': '扇状烈焰',
    'Freeze': '冰冻术',
    'Healing Light': '治愈之光',
    'Heavenly Blast': '天堂冲击',
    'Hollow Flesh': '空心肉体',
    'Hungry Maw': '饥肠怪',
    'Invoke Savagery': '野蛮行事',
    'Magnetize': '磁化术',
    'Melt': '熔化术',
    'Petrify': '石化术',
    'Regeneration Aura': '再生光环',
    'Soul Swap': '灵魂换位',
    'Thunder Strike': '雷击术',
    'Touch of Death': '死亡之触',
    'Toxic Spores': '有毒孢子',
    'Toxin Burst': '毒素爆发',
    'Aether Swap': '以太换位',
    'Basilisk Armor': '蜥怪盔甲',
    'Blinding Light': '眩目之光',
    'Blink': '扑闪术',
    'Choir of Angels': '天使合唱',
    'Combust Poison': '燃烧毒药',
    'Darkness': '黑暗术',
    'Death Chill': '死亡之寒',
    'Devour Mind': '吞噬心灵',
    'Dominate': '支配术',
    'Earthen Sentinel': '大地哨兵',
    'Earthquake': '地震术',
    'Flame Burst': '炎爆术',
    'Flame Gate': '火门术',
    'Frostfire Hydra': '霜火九头龙',
    'Ghostball': '幽灵球',
    'Giant Bear': '巨熊',
    'Glass Orb': '玻璃法球',
    'Holy Armor': '圣甲术',
    'Holy Fire': '圣火术',
    'Iceball': '冰球术',
    'Ironize': '讽刺术',
    'Lightning Halo': '闪电光环',
    'Lightning Spire': '闪电尖塔',
    'Mercurize': '汞化术',
    'Mystic Power': '神秘力量',
    'Mystic Vision': '神秘视觉',
    'Nightmare Aura': '梦魇光环',
    'Pain Mirror': '痛苦之镜',
    'Plague of Filth': '污秽瘟疫',
    'Prison of Thorns': '荆棘监狱',
    'Seal Fate': '封印命运',
    'Shrapnel Blast': '弹片爆破',
    'Silver Spear': '银色标枪',
    'Suspend Mortality': '暂缓死亡',
    'Underworld Passage': '冥界通道',
    'Void Beam': '虚空光束',
    'Void Orb': '虚空法球',
    'Arc Lightning': '弧状闪电',
    'Blizzard': '暴风雪',
    'Bone Barrage': '白骨弹幕',
    'Call Archon': '召唤统领',
    'Call Seraph': '召唤炽天使',
    'Chimera Familiar': '奇美拉佣兽',
    'Conductance': '电导术',
    'Conjure Memories': '唤起记忆',
    'Death Gaze': '死亡凝视',
    'Death Shock': '死亡冲击',
    'Dispersion Field': '扩散场',
    'Essence Flux': '菁华异变',
    'Fiery Tormentor': '火热折磨者',
    'Fire Drake': '火焰巨龙',
    'Ice Drake': '寒冰巨龙',
    'Ice Orb': '寒冰法球',
    'Ice Vortex': '寒冰旋涡',
    'Lightning Form': '闪电形态',
    'Lightning Storm': '闪电风暴',
    'Orb Control': '法球控制',
    'Permanence': '持久术',
    'Petrification Aura': '石化光环',
    'Purity': '纯净术',
    'Pyrostatic Pulse': '静电脉冲',
    'Searing Seal': '灼热封印',
    'Siege Golems': '攻城魔像',
    'Sight of Blood': '鲜血视线',
    'Siphon Shields': '虹吸护罩',
    'Storm Burst': '风暴爆发',
    'Storm Drake': '风暴巨龙',
    'The Restless Dead': '不息的死者',
    'Void Drake': '虚空巨龙',
    'Volcanic Eruption': '火山爆发',
    'Wall of Ice': '寒冰之墙',
    'Watcher Form': '守望者形态',
    'Wheel of Death': '死亡之轮',
    'Ball Lightning': '闪电法球',
    'Blue Lion': '蓝狮子',
    'Cantrip Cascade': '小招倾泻',
    'Chill Wind': '寒风术',
    'Death Cleave': '死亡分裂',
    'Fae Court': '仙灵宫廷',
    'Floating Eye': '漂浮之眼',
    'Flock of Eagles': '召唤鹰群',
    'Heavenly Idol': '天堂雕像',
    'Ice Phoenix': '寒冰凤凰',
    'Mega Annihilate': '超级歼灭术',
    'Pillar of Fire': '火柱术',
    'Pyrostatic Curse': '电焰诅咒',
    'Ring of Spiders': '蜘蛛之环',
    'Slime Form': '史莱姆形态',
    'Soul Tax': '灵魂税',
    'Spider Queen': '蜘蛛女王',
    'Teleport': '传送术',
    'Dragon Roar': '巨龙咆哮',
    'Gold Drake': '黄金巨龙',
    "Heaven's Wrath": '天堂之怒',
    'Imp Swarm': '小鬼群',
    'Mystic Memory': '神秘记忆',
    'Searing Orb': '灼热法球',
    'Twilight Gaze': '暮光凝视',
    'Knightly Oath': '骑士誓言',
    'Meteor Shower': '陨石雨',
    'Multicast': '多重施法',
    'Spikeball Factory': '钉球工厂',
    'Word of Beauty': '美丽真言',
    'Word of Chaos': '混沌真言',
    'Word of Ice': '寒冰真言',
    'Word of Madness': '疯狂真言',
    'Word of Undeath': '不死真言',
    # 玩家咒语分支
    'Chaos Ball': '混沌球',
    'Energy Ball': '能量球',
    'Ash Ball': '灰烬球',
    'Channeling': '引导箭',
    'Judgement Bolt': '审判箭',
    'Energy Bolt': '能量箭',
    'Cascade': '倾泻歼灭',
    'Dark Annihilation': '黑暗歼灭',
    'Arcane Annihilation': '奥术歼灭',
    'Void Teleport': '虚空传送术',
    'Blindcasting': '蔽目施法',
    'Lightning Blink': '闪电扑闪',
    'Dark Blink': '黑暗扑闪',
    'Storm Power': '风暴之力',
    'Heaven Strike': '天堂之击',
    'Extra Bolts': '额外箭矢',
    'Glassify': '璃化术',
    'Blood Hound': '鲜血狼',
    'Ice Hound': '寒冰猎犬',
    'Clay Hound': '黏土猎犬',
    'Wolf Pack': '群狼术',
    'Armored Bear': '装甲巨熊',
    'Venom Bear': '毒液巨熊',
    'Blood Bear': '鲜血巨熊',
    'Venom Beast': '毒液野兽',
    'Poison Bite': '毒性撕咬',
    'Demon Frenzy': '恶魔狂热',
    'Minion Damage': '小兵伤害',
    'Minion Health': '小兵生命',
    'Pounce': '猛扑',
    'Iron Prison': '铁棘监狱',
    'Icy Prison': '冰棘监狱',
    'Thorny Plant': '荆棘植物',
    'Iron Thorn': '铁棘植物',
    'Icy Thorn': '冰棘植物',
    'Cloud Armor': '云甲术',
    'Blood Lust': '嗜血术',
    'Holy Fury': '神圣愤怒',
    'Dark Fury': '黑暗愤怒',
    'Shielding Light': '护盾之光',
    'Global': '全局',
    'Red Dwarf': '红矮星',
    'Void Walk': '虚空漫步',
    'Matter Melting': '物质熔化',
    'Magnetic Pulse': '磁性脉冲',
    'Shielding': '护盾',
    'Freeze Chance': '冻结几率',
    'Orbs': '法球',
    'orbs': '法球',
    'HP Threshold': '生命阈值',
    'Metal Swarm': '金属群',
    'Dark Swarm': '黑暗群',
    'Mega Swarm': '超级群',
    'Spark Imp': '火花小鬼',
    'Copper Imp': '铜质小鬼',
    'Rot Imp': '腐烂小鬼',
    'Giant Imp': '巨型小鬼',
    'Furnace Imp': '熔炉小鬼',
    'Fire Imp': '火焰小鬼',
    'Ioid Imp': '虚空小鬼',
    'Insanity Imp': '疯狂小鬼',
    'Iron Imp': '钢铁小鬼',
    'Vision Aura': '视觉光环',
    'Damage Bonus': '伤害增益',
    'Melting Flame': '熔炎术',
    'Bright Flame': '明炎术',
    'Spreading Flame': '挥炎术',
    'Dragon Mage': '巨龙法师',
    'Essence Drake': '菁华巨龙',
    'Freeze Duration': '冻结持续',
    'Spark': '电火花',
    'Cloud Conductance': '导电云',
    'Lightning Shield': '闪电护盾',
    'Withering': '枯萎',
    'Soul Battery': '灵魂充能',
    'Death Roulette': '死亡轮盘',
    'Voidtouch': '虚空之触',
    'Flametouch': '烈焰之触',
    'Wrathtouch': '愤怒之触',
    'Touch of the Raven': '乌鸦之触',
    'Touch of the Vampire': '吸血鬼之触',
    'Touch of the Reaper': '死神之触',
    'Volcano': '火山术',
    'Forced Transfer': '强制转移',
    'Void Spawning': '虚空孳生',
    'Earthquake Totem': '地震图腾',
    'Stinging Totem': '毒刺图腾',
    'Holy Totem': '神圣图腾',
    'Ghost King': '幽灵国王',
    'Ghost Mass': '幽灵团块',
    'Weave Sorcery': '编织法术',
    'Vampiric Gaze': '吸血鬼凝视',
    'Bone Spears': '白骨长矛',
    'Cursed Bones': '受诅白骨',
    'Shambler Assembly': '蹒跚集结',
    'Shield Burn': '护盾燃烧',
    'Slaughter Bolt': '屠杀弹',
    'Holy Bolt': '神圣弹',
    'Disruption Bolt': '干扰弹',
    'Spirit Eater': '噬魂',
    'Gluttony': '饕餮',
    'Infinite Cascades': '无限倾泻',
    'Ice Penetration': '熔透寒冰',
    'Arcane Insulation': '奥术隔离',
    'Nature Mimicry': '自然模仿',
    'Dark Mimicry': '黑暗模仿',
    'Arcane Mimicry': '奥术模仿',
    'Echo Flash': '回响闪烁',
    'Acidity': '酸性',
    'Summon Queen': '召唤女王',
    'Good Faery': '好仙灵',
    'Glassification Bolt': '璃化弹',
    'Glass Faery': '玻璃仙灵',
    'Spirit Bind': '灵魂绑定',
    'Shield': '护盾',
    'Echo Heal': '回响治疗',
    'Sing': '歌唱',
    'Culling': '宰割',
    'Arcane Taxation': '奥术税',
    'Dark Units': '黑暗单位',
    'Dive Attack': '俯冲攻击',
    'Thunderbirds': '雷鸟',
    'Eagle': '鹰',
    'Claw': '爪击',
    'Dive': '俯冲',
    'Thunderbird': '雷鸟',
    'Flaming Arc': '弧状火焰',
    'Flaming Sword': '火焰剑',
    'Beauty': '美丽',
    'Fire Gaze': '火焰凝视',
    'Golden Crusade': '黄金圣战',
    'Moonblade': '月刃',
    'Essence Aura': '菁华光环',
    'Heal Aura': '治疗光环',
    'Holy Fire Aura': '圣火光环',
    'Seraph': '炽天使',
    'Archon Lightning': '统领闪电',
    'Thunder Stone': '雷石',
    'Thunder Stones': '雷石',
    'Fire Stone': '火石',
    'Fire Stones': '火石',
    'Fire Vulnerability': '火焰易伤',
    'Multicopy': '再多一份',
    'More Shrapnel': '更多弹片',
    'Puncturing Blast': '穿刺爆破',
    'Magnetized Shards': '磁化碎片',
    'Serpent Plague': '巨蛇瘟疫',
    'Frostfire Tormentor': '霜火折磨者',
    'Ghostfire Tormentor': '鬼火折磨者',
    'Bound Knight': '骑士效忠',
    'Void Court': '虚空宫廷',
    'Storm Court': '风暴宫廷',
    'Chaos Court': '混沌宫廷',
    'Grey Mushbooms': '灰色爆菇',
    'Red Mushbooms': '红色爆菇',
    'Glass Mushbooms': '玻璃爆菇',
    'Amplified Poison': '增效毒性',
    'Amplify Venom': '增效毒液',
    'Spread Poison': '传播毒性',
    'Poison Skin': '毒性皮肤',
    'Venom Drinker': '毒液饮者',
    'Resistances': '抗性',
    'Trample Attack': '践踏攻击',
    'Aether Queen': '乙太女王',
    'Steel Queen': '钢铁女王',
    'Reincarnations': '复活',
    'Ice elemental': '寒冰元素',
    'Safety': '安全',
    'Seal of Searing': '灼热封印',
    'Arcane Gaze': '奥术凝视',
    'Flame Tongue': '火焰吐息',
    'Fire Elemental': '火元素',
    'Giant Strength': '巨人之力',
    'Frenzy Bite': '狂热撕咬',
    'Dire Wolf': '恐狼',
    'Earth Elemental': '大地元素',
    'Angelic Singer': '天使歌手',
    'Icicle Harvest': '冰锥收割',
    'Freezing': '冰冻',
    'Fire Slime': '火焰史莱姆',
    'Ice Slime': '寒冰史莱姆',
    'Void Slime': '虚空史莱姆',
    'Junk Golem': '废料魔像',
    'Elemental Spirits': '元素灵魂',
    'Gust of Wind': '劲风吹袭',
    'Manufactory': '制造大厂',
    'Copper Spikeballs': '铜制钉球',
    'Mercurized': '中汞毒',
    'Mercurial Vengeance': '中汞复仇',
    'Morbidity': '发病率',
    'Corrosion': '腐蚀性',
    'Toxic Fumes': '毒雾',
    'Pull Distance': '拉动距离',
    'Universal Magnetism': '通用磁性',
    'Inferno Cannon': '地狱火炮',
    'Golem Siege Mechanic': '攻城魔像技师',
    'Fire Blast': '爆炸起火',
    'Zap': '劈中',
    'Wall Penetration': '墙壁渗透',
    'Resistance Penetration': '抗性渗透',
    'Dark Dream': '黑暗梦境',
    'Electric Dream': '电气梦境',
    'Fever Dream': '狂热梦境',
    'Spark Spirit': '火花灵魂',
    'Fire Lizard': '火蜥蜴',
    'Flame Rift': '火焰裂隙',
    '': '',

    # 玩家被动
    'Arcane Accounting': '奥术节能',
    'Arcane Combustion': '奥术燃烧',
    'Arcane Shield': '奥术护盾',
    'Chaos Buddies': '混沌伙伴',
    'Chastisement': '惩戒',
    'Crystal Power': '水晶之力',
    'Faestone': '仙灵石',
    'Ghostfire': '鬼火',
    'Hibernation': '休眠',
    'Holy Water': '圣水',
    'Hungry Dead': '饿死鬼',
    'Megavenom': '超级毒液',
    'Minion Regeneration': '小兵再生',
    'Natural Vigour': '自然活力',
    'Paralyzing Venom': '麻痹毒液',
    'Radiant Chill': '寒气逼人',
    'Shielded Minions': '带盾小兵',
    'Spider Spawning': '蜘蛛孳生',
    'Unholy Alliance': '不洁联盟',
    'Venom Spit': '毒液喷吐',
    'Voidflame Lantern': '虚空火灯',
    'White Flame': '白色火焰',
    'Acid Fumes': '酸雾',
    'Chaos Casting': '混沌施法',
    'Collected Agony': '收集痛苦',
    'Frozen Fragility': '冻脆',
    'Glittering Dance': '闪光之舞',
    'Horror': '恐怖',
    'Houndlord': '猎犬领主',
    'Hypocrisy': '虚伪',
    'Last Word': '遗言',
    'Lightning Frenzy': '闪电狂潮',
    'Melting Armor': '熔化盔甲',
    'Necrostatics': '尸毒学',
    'Prince of Ruin': '毁灭王子',
    'Purestrike': '纯粹打击',
    'Pyrophilia': '嗜热症',
    'Righteous March': '正义进军',
    'Searing Heat': '灼热',
    'Silkshifter': '织丝者',
    'Storm Caller': '风暴召师',
    'Thorn Garden': '荆棘花园',
    'Bone Guard': '白骨卫士',
    'Cracklevoid': '噼里啪啦',
    'Frostbite': '冻伤',
    'Ice Tap': '冰塔',
    'Icy Vengeance': '冰冷复仇',
    'Inferno Engines': '地狱火引擎',
    'Lightning Warp': '闪电扭曲',
    'Moonspeaker': '月语者',
    'Scalespinner': '龙鳞旋抗',
    'Shatter Shards': '破碎飞片',
    'Starfire': '星星之火',
    'Steam Anima': '蒸汽灵魂',
    'Arch Conjurer': '大造物师',
    'Arch Enchanter': '大附魔师',
    'Arch Sorcerer': '大法术师',
    'Dark Lord': '黑暗领主',
    'Dragon Lord': '巨龙领主',
    'Fiery Judgement': '炽热审判',
    'Fire Lord': '火焰领主',
    'Holy Thunder': '神圣雷霆',
    'Ice Lord': '寒冰领主',
    'Light Lord': '光明领主',
    'Metal Lord': '金属领主',
    'Nature Lord': '自然领主',
    'Orb Lord': '法球领主',
    'Shock Value': '冲击价值',
    'Soul Harvest': '灵魂收割',
    'Thunder Lord': '雷霆领主',
    'Translocation Master': '转移大师',
    'Unblinking Eye': '定睛之眼',
    'Void Lord': '虚空领主',
    'Void Spikes': '虚空尖塔',
    # 物品
    'Healing Potion': '治疗药水',
    'Teleporter': '传送器',
    'Chaos Bell': '混沌之铃',
    'Golden Stopwatch': '黄金秒表',
    'Death Dice': '死亡骰子',
    'Energy Shield': '能量护盾',
    'Stone Shield': '石质护盾',
    'Mana Potion': '魔法药水',
    'Earthquake Orb': '地震法球',
    'Dragon Horn': '巨龙号角',
    'Portal Disruptor': '传送门干扰器',
    'Shrine Disruptor': '祭祠干扰器',
    'Portal Key': '传送门钥匙',
    'Orb of Corruption': '腐败法球',
    'Elixir of Youth': '不老琼浆',
    'Youth': '永葆青春',
    'Aether Dagger': '以太匕首',
    'Oculus': '天眼',
    'Memory Enhancement': '记忆增强',
    'Draught of Memories': '记忆药剂',
    'Bag of Spikes': '一袋钉子',
    'Bag of Bags': '一袋袋子',
    'Troll Crown': '巨魔之冠',
    'Storm Troll Crown': '风暴巨魔之冠',
    'Earth Troll Crown': '大地巨魔之冠',

    'Goblin': '哥布林',
    'Bat': '蝙蝠',

    'Bag of Bugs': '一袋虫子',
    'Rolling Spike Ball': '滚动钉球',

    'Gate': '大门',

    'Memory Orb': '记忆法珠',
}
tag_dic = {
    'Fire': 'F 火焰',
    'Lightning': 'L 闪电',
    'Ice': 'I 寒冰',
    'Nature': 'N 自然',
    'Arcane': 'A 奥术',
    'Dark': 'D 黑暗',
    'Holy': 'H 神圣',
    'Sorcery': 'S 法术',
    'Conjuration': 'C 召唤',
    'Enchantment': 'E 附魔',
    'Word': 'W 真言',
    'Orb': 'B 法球',
    'Dragon': 'R 巨龙',
    'Translocation': 'T 移位',
    'Metallic': 'M 金属',
    'Eye': 'Y 视线',
    'Chaos': 'O 混沌'
}
attrc_dic = {
    'radius': '格',
    'damage': '点',
    'max_charges': '点',
    'range': '格',
    'num_targets': '个',
    'stun_duration': '个',
    'minion_range': '格',
    'minion_duration': '个',
    'minion_damage': '点',
    'heal': '点',
    'minion_health': '点',
    'cascade_range': '格',
    'dark': '次',
    'arcane': '次',
    'meteor_size': '点',
    'max_channel': '个',
    'void_teleport': '个数',
    'shield_burn': '点',
    'duration': '个',
}
attr_dic = {
    'radius': '半径',
    'damage': '伤害',
    'max_charges': '充能上限',
    'range': '射程',
    'num_targets': '目标数量',
    'stun_duration': '击晕回合',
    'minion_range': '小兵射程',
    'minion_duration': '小兵持续回合',
    'minion_damage': '小兵伤害',
    'heal': '治疗',
    'minion_health': '小兵生命',
    'cascade_range': '倾泻射程',
    'dark': '黑暗伤害命中',
    'arcane': '奥术伤害命中',
    'meteor_size': '陨石尺寸',
    'max_channel': '引导回合上限',
    'void_teleport': '虚空传送数',
    'shield_burn': '护盾燃烧',
    'duration': '持续回合',
    'bolt': '箭矢',
    'extra_damage': '额外伤害',
    'damage type': '伤害类型',
    'hound': '猎犬',
    'requires_los': '无需视线',
    'lightning_blink': '闪电扑闪',
    'dark_blink': '黑暗扑闪',
    'storm_power': '风暴之力',
    'heaven_strike': '天堂之击',
    'glassify': '璃化',
    'petrify_duration': '石化持续',
    'leap_range': '跳跃范围',
    'blood_hound': '鲜血猎犬',
    'ice_hound': '寒冰猎犬',
    'clay_hound': '黏土猎犬',
    'wolf_pack': '群狼术',
    'demon_units': '恶魔单位',
    'wither': '枯萎',
    'soulbattery': '灵魂充能',
    'freezing': '冰冻',
    'icicle_harvest': '冰锥收割',
    'acidicy': '酸性',
    'species': '种族',
    'prison': '监狱',
    'dream': '梦境',
    'swarm': '虫群',
    'flame': '火焰',
    'raising': '复活',
    'totem': '图腾',
    'center summon': '中心召唤物',
    'aura': '光环',
    'variant': '变化',
    'court': '宫廷',
    'color': '颜色'
}