dic = {
    # 属性 大小写
    "arcane": "奥术",
    "Arcane": "奥术",
    "chaos": "混沌",
    "Chaos": "混沌",
    "Conjuration": "召唤",
    "conjuration": "召唤",
    "Dark": "黑暗",
    "dark": "黑暗",
    "dragon": "巨龙",
    "Dragon": "巨龙",
    "Enchantment": "附魔",
    "enchantment": "附魔",
    "Eye": "视线",
    "eye": "视线",
    "fire": "火焰",
    "Fire": "火焰",
    "holy": "神圣",
    "Holy": "神圣",
    "Ice": "寒冰",
    "ice": "寒冰",
    "Lightning": "闪电",
    "lightning": "闪电",
    "Metallic": "金属",
    "metallic": "金属",
    "Nature": "自然",
    "nature": "自然",
    "Orb": "法球",
    "orb": "法球",
    "sorcery": "法术",
    "Sorcery": "法术",
    "Translocation": "移位",
    "translocation": "移位",
    "Word": "真言",
    "word": "真言",
    # 其他常用 大小写
    "acid": "酸性",
    "Acid": "酸性",
    "Arrow": "箭矢",
    "arrow": "箭矢",
    "berserk": "狂暴",
    "Berserk": "狂暴",
    "blind": "致盲",
    "Blind": "致盲",
    "blinded": "致盲",
    "Blinded": "致盲",
    "buff_apply": "施加增益",
    "Buff_Apply": "施加增益",
    "Construct": "造物",
    "construct": "造物",
    "damage": "伤害",
    "Damage": "伤害",
    "debuff_apply": "施加减益",
    "Debuff_Apply": "施加减益",
    "demon": "恶魔",
    "Demon": "恶魔",
    "Elemental": "元素",
    "elemental": "元素",
    "flying": "飞行",
    "Flying": "飞行",
    "frozen": "冻结",
    "Frozen": "冻结",
    "glass": "玻璃",
    "Glass": "玻璃",
    "Glassification": "璃化",
    "glassification": "璃化",
    "Glassified": "璃化",
    "glassified": "璃化",
    "heal": "治疗",
    "Heal": "治疗",
    "Leap": "跳跃",
    "leap": "跳跃",
    "Living": "活物",
    "living": "活物",
    "max charges": "充能上限",
    "Max Charges": "充能上限",
    "Petrification": "石化",
    "petrification": "石化",
    "petrified": "石化",
    "Petrified": "石化",
    "Physical": "物理",
    "physical": "物理",
    "Poison": "毒性",
    "poison": "毒性",
    "Poisoned": "中毒",
    "poisoned": "中毒",
    "Radius": "半径",
    "radius": "半径",
    "Shield_Apply": "施加护盾",
    "shield_apply": "施加护盾",
    "Shield_Expire": "护盾期满",
    "shield_expire": "护盾期满",
    "Slime": "史莱姆",
    "slime": "史莱姆",
    "Sound_Effect": "音效",
    "sound_effect": "音效",
    "spider": "蜘蛛",
    "Spider": "蜘蛛",
    "Stun": "击晕",
    "stun": "击晕",
    "Stunned": "击晕",
    "stunned": "击晕",
    "Tongue": "舌头",
    "tongue": "舌头",
    "Undead": "不死",
    "undead": "不死",
    # 玩家咒语
    "Aether Swap": "以太换位",
    "Annihilate": "歼灭术",
    "Arc Lightning": "弧状闪电",
    "Ball Lightning": "闪电法球",
    "Basilisk Armor": "蜥怪盔甲",
    "Blazerip": "熔刃术",
    "Blinding Light": "眩目之光",
    "Blink": "扑闪术",
    "Blizzard": "暴风雪",
    "Blue Lion": "蓝色狮子",
    "Boiling Blood": "热血术",
    "Bone Barrage": "白骨弹幕",
    "Call Archon": "召唤统领",
    "Call Seraph": "召唤炽天使",
    "Cantrip Cascade": "小招倾泻",
    "Chain Lightning": "闪电链",
    "Chaos Barrage": "混沌箭雨",
    "Chill Wind": "寒风术",
    "Chimera Familiar": "奇美拉佣兽",
    "Choir of Angels": "天使合唱",
    "Cloud Nova": "风云新星",
    "Combust Poison": "燃烧毒药",
    "Conductance": "电导术",
    "Conjure Memories": "唤起记忆",
    "Darkness": "黑暗术",
    "Death Bolt": "死亡之箭",
    "Death Chill": "死亡之寒",
    "Death Cleave": "死亡分裂",
    "Death Gaze": "死亡凝视",
    "Death Shock": "死亡冲击",
    "Devour Mind": "吞噬心智",
    "Disperse": "驱散术",
    "Dispersion Field": "扩散场",
    "Dominate": "支配术",
    "Dragon Roar": "巨龙咆哮",
    "Earthen Sentinel": "大地哨兵",
    "Earthquake": "地震术",
    "Essence Flux": "菁华异变",
    "Eye of Fire": "火焰之眼",
    "Eye of Ice": "寒冰之眼",
    "Eye of Lightning": "闪电之眼",
    "Eye of Rage": "愤怒之眼",
    "Fae Court": "仙灵宫廷",
    "Fan of Flames": "扇状烈焰",
    "Fiery Torment": "火热折磨",
    "Fiery Tormentor": "火热折磨者",
    "Fire Drake": "火焰巨龙",
    "Fireball": "火球术",
    "Flame Burst": "炎爆术",
    "Flame Gate": "火门术",
    "Floating Eye": "漂浮之眼",
    "Flock of Eagles": "召唤鹰群",
    "Freeze": "冰冻术",
    "Frostfire Hydra": "霜火多头龙",
    "Ghostball": "幽灵球",
    "Giant Bear": "巨熊",
    "Glass Orb": "玻璃法球",
    "Gold Drake": "黄金巨龙",
    "Healing Light": "治愈之光",
    "Heaven's Wrath": "天堂之怒",
    "Heavenly Blast": "天堂冲击",
    "Heavenly Idol": "天堂雕像",
    "Hollow Flesh": "空心肉体",
    "Holy Armor": "圣甲术",
    "Holy Fire": "圣火术",
    "Hungry Maw": "饥肠怪",
    "Ice Drake": "寒冰巨龙",
    "Ice Orb": "寒冰法球",
    "Ice Phoenix": "寒冰凤凰",
    "Ice Vortex": "寒冰漩涡",
    "Iceball": "冰球术",
    "Icicle": "冰锥术",
    "Imp Swarm": "小鬼群",
    "Invoke Savagery": "野蛮行事",
    "Ironize": "铁化术",
    "Ironized": "铁化",
    "Knightly Oath": "骑士誓言",
    "Lightning Bolt": "闪电箭",
    "Lightning Form": "闪电形态",
    "Lightning Halo": "闪电光环",
    "Lightning Spire": "闪电尖塔",
    "Lightning Storm": "闪电风暴",
    "Linear Conductance": "直线电导",
    "Magic Missile": "魔法飞弹",
    "Magnetize": "磁化术",
    "Mega Annihilate": "超级歼灭术",
    "Melt": "熔化术",
    "Mercurize": "汞化术",
    "Meteor Shower": "陨石雨",
    "Multicast": "多重施法",
    "Mystic Memory": "神秘记忆",
    "Mystic Power": "神秘力量",
    "Mystic Vision": "神秘视觉",
    "Nightmare Aura": "梦魇光环",
    "Orb Control": "法球控制",
    "Pain Mirror": "痛苦之镜",
    "Permanence": "持久术",
    "Petrification Aura": "石化光环",
    "Petrify": "石化术",
    "Pillar of Fire": "火柱术",
    "Plague of Filth": "污秽瘟疫",
    "Poison Sting": "毒刺术",
    "Prison of Thorns": "荆棘监狱",
    "Purity": "纯净术",
    "Pyrostatic Curse": "电焰诅咒",
    "Pyrostatic Pulse": "电焰脉冲",
    "Regeneration Aura": "再生光环",
    "Ring of Spiders": "蜘蛛之环",
    "Seal Fate": "封印命运",
    "Searing Orb": "灼热法球",
    "Searing Seal": "灼热封印",
    "Shrapnel Blast": "弹片冲击",
    "Siege Golems": "攻城魔像",
    "Sight of Blood": "鲜血视线",
    "Silver Spear": "银色标枪",
    "Siphon Shields": "虹吸护罩",
    "Slime Form": "史莱姆形态",
    "Soul Swap": "灵魂换位",
    "Soul Tax": "灵魂税",
    "Spider Queen": "蜘蛛女王",
    "Spikeball Factory": "钉球工厂",
    "Storm Burst": "风暴爆发",
    "Storm Drake": "风暴巨龙",
    "Suspend Mortality": "暂缓死亡",
    "Teleport": "传送术",
    "The Restless Dead": "不息的死者",
    "Thunder Strike": "雷击术",
    "Touch of Death": "死亡之触",
    "Toxic Spores": "有毒孢子",
    "Toxin Burst": "毒素爆发",
    "Twilight Gaze": "暮光凝视",
    "Underworld Passage": "冥界通道",
    "Void Beam": "虚空光束",
    "Void Drake": "虚空巨龙",
    "Void Orb": "虚空法球",
    "Void": "虚空",
    "Volcanic Eruption": "火山爆发",
    "Wall of Ice": "寒冰之墙",
    "Watcher Form": "守卫形态",
    "Wheel of Death": "死亡之轮",
    "Wolf": "召狼术",
    "Word of Beauty": "美丽真言",
    "Word of Chaos": "混沌真言",
    "Word of Ice": "寒冰真言",
    "Word of Madness": "疯狂真言",
    "Word of Undeath": "不死真言",
    # 玩家咒语派生
    "Acidicy": "酸性",
    "Acidity": "酸性",
    "Aether Queen": "乙太女王",
    "Aether Spiders": "乙太蜘蛛",
    "Amplified Poison": "增效毒性",
    "Amplify Venom": "增效毒液",
    "Angelic Singer": "天使歌手",
    "Arcane Annihilation": "奥术歼灭",
    "Arcane Casting": "奥术施法",
    "Arcane Gaze": "奥术凝视",
    "Arcane Insulation": "奥术隔离",
    "Arcane Mimicry": "奥术模仿",
    "Arcane Taxation": "奥术税",
    "Archon Lightning": "统领闪电",
    "Armored Bear": "装甲巨熊",
    "Ash Ball": "灰烬球",
    "Aura": "光环",
    "Beauty": "美丽",
    "Berserk Duration": "狂暴回合",
    "Blindcasting": "无需视线",
    "Blood Bear": "鲜血巨熊",
    "Blood Hound": "鲜血狼",
    "Blood Lust": "嗜血术",
    "Bolt": "箭矢",
    "Bone Spears": "白骨长矛",
    "Bonus": "增益",
    "Bound Knight": "骑士效忠",
    "Breath Damage": "吐息伤害",
    "Bright Flame": "明炎术",
    "Brute Force": "蛮力",
    "Cascade Range": "倾泻射程",
    "Cascade": "倾泻歼灭",
    "Center Summon": "中心召唤物",
    "Channeling": "可引导",
    "Chaos Ball": "混沌球",
    "Chaos Court": "混沌宫廷",
    "Charges Regained": "充能获取",
    "Check Cur Hp": "检查当前生命",
    "Claw": "爪击",
    "Clay Hound": "黏土猎犬",
    "Cloud Armor": "云甲术",
    "Cloud Conductance": "导电云",
    "Cloudform": "云形态",
    "Color": "颜色",
    "Copies": "复制",
    "Copper Imp": "铜质小鬼",
    "Copper Spikeballs": "铜制钉球",
    "Corrosion": "腐蚀性",
    "Court": "宫廷",
    "Culling": "宰割",
    "Cursed Bones": "受诅白骨",
    "Damage Bonus": "伤害增益",
    "Damage Type": "伤害类型",
    "Dark Annihilation": "黑暗歼灭",
    "Dark Blink": "黑暗扑闪",
    "Dark Casting": "黑暗施法",
    "Dark Dream": "黑暗梦境",
    "Dark Fury": "黑暗愤怒",
    "Dark Mimicry": "黑暗模仿",
    "Dark Swarm": "黑暗群",
    "Dark Units": "黑暗单位",
    "Death Roulette": "死亡轮盘",
    "Demon Frenzy": "恶魔狂热",
    "Demon Units": "恶魔单位",
    "Dire Wolf": "恐狼",
    "Disruption Bolt": "干扰弹",
    "Dive Attack": "俯冲攻击",
    "Dive": "俯冲",
    "Dragon Mage": "巨龙法师",
    "Drake Swap": "巨龙换位",
    "Dream": "梦境",
    "Duration": "持续回合",
    "Eagle": "鹰",
    "Earth Elemental": "大地元素",
    "Earthquake Totem": "地震图腾",
    "Echo Flash": "回响闪烁",
    "Echo Heal": "回响治疗",
    "Electric Dream": "电气梦境",
    "Elemental Spirits": "元素灵魂",
    "Energy Ball": "能量球",
    "Energy Bolt": "能量箭",
    "Essence Aura": "菁华光环",
    "Essence Drake": "菁华巨龙",
    "Extra Bolts": "额外箭矢",
    "Extra Damage": "额外伤害",
    "Fever Dream": "狂热梦境",
    "Fire Blast": "火焰冲击",
    "Fire Elemental": "火元素",
    "Fire Gaze": "火焰凝视",
    "Fire Imp": "火焰小鬼",
    "Fire Lizard": "火蜥蜴",
    "Fire Slime": "火焰史莱姆",
    "Fire Stone": "火石",
    "Fire Stones": "火石",
    "Fire Vulnerability": "火焰易伤",
    "Flame Rift": "火焰裂隙",
    "Flame Tongue": "火焰吐息",
    "Flame": "火焰",
    "Flametouch": "烈焰之触",
    "Flaming Arc": "弧状火焰",
    "Flaming Sword": "火焰剑",
    "Forced Transfer": "强制转移",
    "Freeze Chance": "冻结几率",
    "Freeze Duration": "冻结持续回合",
    "Freezing": "冰冻",
    "Frenzy Bite": "狂热撕咬",
    "Frostfire Tormentor": "霜火折磨者",
    "Furnace Imp": "熔炉小鬼",
    "Ghost King": "幽灵国王",
    "Ghost Mass": "幽灵群",
    "Ghostfire Tormentor": "鬼火折磨者",
    "Giant Imp": "巨型小鬼",
    "Giant Strength": "巨人之力",
    "Glass Faery": "玻璃仙灵",
    "Glass Mushbooms": "玻璃爆菇",
    "Glassification Bolt": "璃化弹",
    "glassify": "璃化",
    "Glassify": "璃化术",
    "Global": "全图光环",
    "Gluttony": "饕餮",
    "Golden Crusade": "黄金圣战",
    "Golem Siege Mechanic": "攻城魔像技师",
    "Good Faery": "好仙灵",
    "Grey Mushbooms": "灰色爆菇",
    "Gust of Wind": "劲风吹袭",
    "Heal Aura": "治疗光环",
    "Heaven Strike": "天堂之击",
    "Holy Bolt": "神圣弹",
    "Holy Fire Aura": "圣火光环",
    "Holy Fury": "神圣愤怒",
    "Holy Totem": "神圣图腾",
    "Holy Vulnerability": "神圣易伤",
    "Hound": "猎犬",
    "Hp Bonus": "生命加成",
    "HP Threshold": "生命阈值",
    "Hp Threshold": "生命阈值",
    "Ice Crush": "寒冰压溃",
    "Ice elemental": "寒冰元素",
    "Ice Hound": "寒冰猎犬",
    "Ice Penetration": "熔透寒冰",
    "Ice Slime": "寒冰史莱姆",
    "Icicle Harvest": "冰锥收割",
    "Icy Prison": "冰棘监狱",
    "Icy Thorn": "冰棘植物",
    "Inferno Cannon": "地狱火炮",
    "Infinite Cascades": "无限倾泻",
    "Insanity Imp": "疯狂小鬼",
    "Intensity": "强度",
    "Ioid Imp": "虚空小鬼",
    "Iron Imp": "钢铁小鬼",
    "Iron Prison": "铁棘监狱",
    "Iron Thorn": "铁棘植物",
    "Judgement Bolt": "审判箭",
    "Junk Golem": "废料魔像",
    "Junk Golems": "废料魔像",
    "Leap Range": "跳跃范围",
    "Lightning Blink": "闪电扑闪",
    "Lightning Shield": "闪电护盾",
    "Lives": "命",
    "Magnetic Pulse": "磁性脉冲",
    "Magnetized Shards": "磁化碎片",
    "Manufactory": "制造大厂",
    "Matter Melting": "物质熔化",
    "Max Channel": "引导回合上限",
    "Max Health Loss": "失去生命上限",
    "Mega Swarm": "超级群",
    "Melting Flame": "熔炎术",
    "Mercurial Vengeance": "中汞复仇",
    "Mercurized": "中汞毒",
    "Metal Swarm": "金属群",
    "Meteor Size": "陨石尺寸",
    "Minion Attacks": "小兵攻击",
    "Minion Damage": "小兵伤害",
    "Minion Duration": "小兵持续回合",
    "Minion Health": "小兵生命",
    "Minion Physical Resist": "小兵物理抗性",
    "Minion Range": "小兵射程",
    "Minion Resists": "小兵抗性",
    "Moonblade": "月刃",
    "Morbidity": "发病率",
    "More Shrapnel": "更多弹片",
    "Multicopy": "再多一份",
    "Multiplier": "倍率",
    "Nature Casting": "自然施法",
    "Nature Mimicry": "自然模仿",
    "Num Summons": "召唤数量",
    "Num Targets": "目标数量",
    "orbs": "法球",
    "Orbs": "法球",
    "Petrify Duration": "石化持续回合",
    "Poison Bite": "毒性撕咬",
    "Poison Skin": "毒性皮肤",
    "Pounce": "猛扑",
    "Prison": "监狱",
    "Pull Distance": "拉动距离",
    "Puncturing Blast": "穿刺爆破",
    "Raising": "复活",
    "Red Dwarf": "红矮星",
    "Red Mushbooms": "红色爆菇",
    "Reincarnations": "复活",
    "Requires Los": "无需视线",
    "Resist": "抗性",
    "Resistance Debuff": "抗性减益",
    "Resistance Penetration": "抗性渗透",
    "Resistances": "抗性",
    "Resists": "抗性",
    "Rot Imp": "腐烂小鬼",
    "Safety": "安全",
    "Seal of Searing": "灼热封印",
    "Seraph": "炽天使",
    "Serpent Plague": "巨蛇瘟疫",
    "Shambler Assembly": "蹒跚集结",
    "Shield Burn": "护盾燃烧",
    "Shield": "护盾",
    "Shielding Light": "护盾之光",
    "Shielding": "护盾",
    "Shields": "护盾",
    "Shot Cooldown": "射击回合间隔",
    "Sing": "歌唱",
    "Slaughter Bolt": "屠杀弹",
    "Soul Battery": "灵魂充能",
    "Soulbattery": "灵魂充能",
    "Spark Imp": "电光小鬼",
    "Spark Spirit": "电光灵魂",
    "Spark": "电光",
    "Species": "种族",
    "Spirit Bind": "灵魂绑定",
    "Spirit Eater": "噬魂",
    "Spread Poison": "传播毒性",
    "Spreading Curse": "传播诅咒",
    "Spreading Flame": "挥炎术",
    "Steel Queen": "钢铁女王",
    "Stinging Totem": "毒刺图腾",
    "Storm Court": "风暴宫廷",
    "Storm Power": "风暴之力",
    "Stun Duration": "击晕回合",
    "Summon Queen": "召唤女王",
    "Swarm": "虫群",
    "Thorny Plant": "荆棘植物",
    "Thunder Stone": "雷石",
    "Thunder Stones": "雷石",
    "Thunderbird": "雷鸟",
    "Thunderbirds": "雷鸟",
    "Totem": "图腾",
    "Touch of the Raven": "乌鸦之触",
    "Touch of the Reaper": "死神之触",
    "Touch of the Vampire": "吸血鬼之触",
    "Toxic Fumes": "毒雾",
    "Trample Attack": "践踏攻击",
    "Universal Magnetism": "通用磁性",
    "Vampiric Gaze": "吸血鬼凝视",
    "Variant": "变化",
    "Venom Bear": "毒液巨熊",
    "Venom Beast": "毒液野兽",
    "Venom Drinker": "毒液饮者",
    "Vision Aura": "视觉光环",
    "Void Court": "虚空宫廷",
    "Void Slime": "虚空史莱姆",
    "Void Spawning": "虚空孳生",
    "Void Teleport": "虚空传送术",
    "Void Walk": "虚空漫步",
    "Voidtouch": "虚空之触",
    "Volcano": "火山术",
    "Wall Penetration": "墙壁渗透",
    "Wallcano": "墙壁爆发",
    "Weave Sorcery": "编织法术",
    "Wither": "枯萎",
    "Withering": "枯萎",
    "Wolf Pack": "群狼术",
    "Wrathtouch": "愤怒之触",
    "Zap": "劈中",
    # 玩家被动
    "Acid Fumes": "酸雾",
    "Arcane Accounting": "奥术节能",
    "Arcane Combustion": "奥术燃烧",
    "Arcane Shield": "奥术护盾",
    "Arch Conjurer": "大造物师",
    "Arch Enchanter": "大附魔师",
    "Arch Sorcerer": "大法术师",
    "Bone Guard": "白骨卫士",
    "Chaos Buddies": "混沌伙伴",
    "Chaos Casting": "混沌施法",
    "Chastisement": "惩戒",
    "Collected Agony": "收集痛苦",
    "Cracklevoid": "噼里啪啦",
    "Crystal Power": "水晶之力",
    "Dark Lord": "黑暗领主",
    "Dragon Lord": "巨龙领主",
    "Faestone": "仙灵石",
    "Fiery Judgement": "炽热审判",
    "Fire Lord": "火焰领主",
    "Frostbite": "冻伤",
    "Frozen Fragility": "冻脆",
    "Ghostfire": "鬼火",
    "Glittering Dance": "闪光之舞",
    "Hibernation": "休眠",
    "Holy Thunder": "神圣雷霆",
    "Holy Water": "圣水",
    "Horror": "恐怖",
    "Houndlord": "猎犬领主",
    "Hungry Dead": "饿死鬼",
    "Hypocrisy": "虚伪",
    "Ice Lord": "寒冰领主",
    "Ice Tap": "寒冰塔",
    "Icy Vengeance": "寒冰复仇",
    "Inferno Engine": "地狱火引擎",
    "Inferno Engines": "地狱火引擎",
    "Last Word": "最后真言",
    "Light Lord": "光明领主",
    "Lightning Frenzy": "闪电狂潮",
    "Lightning Warp": "闪电扭曲",
    "Megavenom": "超级毒液",
    "Melting Armor": "熔化盔甲",
    "Metal Lord": "金属领主",
    "Minion Regeneration": "小兵再生",
    "Moonspeaker": "月语者",
    "Natural Vigour": "自然活力",
    "Nature Lord": "自然领主",
    "Necrostatics": "尸毒学",
    "Orb Lord": "法球领主",
    "Paralyzing Venom": "麻痹毒液",
    "Prince of Ruin": "毁灭王子",
    "Purestrike": "纯粹打击",
    "Pyrophilia": "嗜热症",
    "Radiant Chill": "寒气逼人",
    "Righteous March": "正义进军",
    "Scalespinner": "龙鳞旋抗",
    "Searing Heat": "灼热",
    "Shatter Shards": "破碎飞片",
    "Shielded Minions": "带盾小兵",
    "Shock Value": "冲击价值",
    "Silkshifter": "织丝者",
    "Soul Harvest": "灵魂收割",
    "Spider Spawning": "蜘蛛孳生",
    "Starfire": "星星之火",
    "Steam Anima": "蒸汽灵魂",
    "Storm Caller": "风暴召师",
    "Thorn Garden": "荆棘花园",
    "Thunder Lord": "雷霆领主",
    "Translocation Master": "转移大师",
    "Unblinking Eye": "定睛之眼",
    "Unholy Alliance": "不洁联盟",
    "Venom Spit": "毒液喷吐",
    "Void Lord": "虚空领主",
    "Void Spikes": "虚空尖塔",
    "Voidflame Lantern": "虚空火灯",
    "White Flame": "白色火焰",
    # 玩家被动派生
    "Burning Ghost": "燃烧的幽灵",
    "Crackling Frenzy": "爆响狂潮",
    "Fae Stone": "仙灵石",
    "Fae Thorn": "仙灵荆棘",
    "Hell Hound": "地狱猎犬",
    "Hunger": "饥饿",
    "Lycanthropy": "狼人",
    "Natural Healing": "自然治疗",
    "Pyrostatics": "电焰",
    "Rock Collection": "岩石收藏",
    "Spin Web": "织蛛网",
    "Starcharged": "星光充能",
    "Steam Elemental": "蒸汽元素",
    # 物品
    "Aether Dagger": "以太匕首",
    "Arcane Circle": "奥术之环",
    "Bag of Bags": "袋子口袋",
    "Bag of Spikes": "钉子口袋",
    "Chaos Bell": "混沌之铃",
    "Chaos Circle": "混沌之环",
    "Clarity": "明晰",
    "Conjuration Circle": "召唤之环",
    "Dark Circle": "黑暗之环",
    "Death Dice": "死亡骰子",
    "Dragon Circle": "巨龙之环",
    "Dragon Horn": "巨龙号角",
    "Draught of Memories": "记忆药剂",
    "Earth Troll Crown": "大地巨魔之冠",
    "Earthquake Orb": "地震法球",
    "Elixir of Youth": "不老琼浆",
    "Enchantment Circle": "附魔之环",
    "Energy Shield": "能量护盾",
    "Eye Circle": "视线之环",
    "Fire Circle": "火焰之环",
    "Gate": "大门",
    "Gold": "黄金",
    "Golden Stopwatch": "黄金秒表",
    "Heal Dot": "治愈点",
    "Healing Potion": "治疗药水",
    "Holy Circle": "神圣之环",
    "Ice Circle": "寒冰之环",
    "Immobilized": "固定",
    "Lightning Circle": "闪电之环",
    "Mana Potion": "魔法药水",
    "Memory Enhancement": "记忆增强",
    "Memory Orb": "记忆球",
    "Metallic Circle": "金属之环",
    "Nature Circle": "自然之环",
    "Oculus": "天眼",
    "Orb Circle": "法球之环",
    "Orb of Corruption": "腐败法球",
    "Portal Disruptor": "裂隙干扰器",
    "Portal Key": "裂隙钥匙",
    "Rift": "裂隙",
    "Ruby Heart": "红宝心",
    "Running Away": "逃跑",
    "Shop": "商店",
    "Shrine Disruptor": "神龛扰乱器",
    "Siege Machine": "攻城机器",
    "Sorcery Circle": "法术之环",
    "Spell Recharge": "咒语充能",
    "Stone Shield": "石质护盾",
    "Storm Troll Crown": "风暴巨魔之冠",
    "Teleporter": "传送器",
    "Tile": "地块",
    "Translocation Circle": "移位之环",
    "Troll Crown": "巨魔之冠",
    "Unnamed Item": "无名物品",
    "Unnamed buff": "无名增益",
    "Unnamed spell": "无名咒语",
    "Unnamed": "无名",
    "Word Circle": "真言之环",
    "Youth": "永葆青春",
    # 怪物和怪物咒语
    "Acrinar, Green Mushboom King": "绿爆菇王克纳",
    "Aelf Aethermancer": "妖精乙太术士",
    "Aelf Arachnomancer": "妖精蜘蛛术士",
    "Aelf Elite": "妖精精锐",
    "Aelf Lightning Artist": "精灵闪电艺术家",
    "Aelf Siege Engineer": "妖精攻城技师",
    "Aelf": "精灵",
    "Aesir": "亚萨",
    "Aether Arachnid Abombination": "乙太蛛形憎恶",
    "Aether Charge": "乙太冲锋",
    "Aether Prism": "乙太棱镜",
    "Aether Spider Queen": "乙太蜘蛛女王",
    "Aether Spider": "乙太蜘蛛",
    "Akabalah, Orc King": "半兽人王阿卡巴拉",
    "Arachnid Abombination": "蛛形憎恶",
    "Arachnid Wizard": "蛛形巫师",
    "Arcane Blast": "乙太冲击",
    "Armored Centaur": "装甲半人马",
    "Armored Efreet": "装甲魔神",
    "Armored Fire Drake": "装甲火焰巨龙",
    "Armored Fire Lizard": "装甲火焰蜥蜴",
    "Armored Fire Wyrm": "装甲火焰浮龙",
    "Armored Flame Toad": "装甲烈焰蟾蜍",
    "Armored Goblin": "装甲哥布林",
    "Armored Gold Drake": "装甲黄金巨龙",
    "Armored Ice Lizard": "装甲寒冰蜥蜴",
    "Armored Ice Wyrm": "装甲寒冰浮龙",
    "Armored Minotaur": "装甲牛头怪",
    "Armored Ogre": "装甲食人魔",
    "Armored Orc": "装甲半兽人",
    "Armored Polar Bear": "装甲北极熊",
    "Armored Satyr": "装甲萨特",
    "Armored Storm Drake": "装甲风暴巨龙",
    "Armored Storm Troll": "装甲风暴巨魔",
    "Armored Vampire": "装甲吸血鬼",
    "Armored Void Drake": "装甲虚空巨龙",
    "Armored Void Toad": "装甲虚空蟾蜍",
    "Army of Hades": "哈迪斯大军",
    "Arrow of Flame": "烈焰之箭",
    "Arrow of Halting": "定身之箭",
    "Arrow of Poison": "毒性之箭",
    "Ash Blast": "灰烬冲击",
    "Ash Bolt": "灰烬箭",
    "Ash Fiend": "灰烬恶鬼",
    "Ash Imp": "灰烬小鬼",
    "Assemble Bone Knight": "组装白骨骑士",
    "Aura of Clarity": "明晰光环",
    "Aura of Life": "生命光环",
    "Aura of Undeath": "不死光环",
    "Aura of Woe": "悲哀光环",
    "Avian Wizard": "鸟形巫师",
    "Awaken Bone Shamblers": "白骨蹒跚醒转者",
    "Axe": "斧子",
    "Baby Aether Spider": "乙太蜘蛛宝宝",
    "Baby Giant Spider": "巨型蜘蛛宝宝",
    "Baby Steel Spider": "钢铁蜘蛛宝宝",
    "Baby Troubler": "麻烦鬼宝宝",
    "Bag of Brain Flies": "脑蝇口袋",
    "Bag of Bugs": "虫子口袋",
    "Bag of Fire Flies": "萤火虫口袋",
    "Bag of Lightning Bugs": "电虫口袋",
    "Ball of Starfire": "星火球",
    "Ballista": "弩炮",
    "Bat Dragon": "蝙蝠巨龙",
    "Bat": "蝙蝠",
    "Beasts of Earth": "大地野兽",
    "Beckon Dragons": "召唤巨龙",
    "Big Troubler": "大麻烦鬼",
    "Bit": "咬",
    "Black Rider": "饥荒之黑骑士",
    "Blackblaze Shaman": "黑焰萨满",
    "Blackfire Aura": "黑火光环",
    "Blinding Powder": "致盲粉",
    "Blizzard Beast": "暴风雪野兽",
    "Blood Tax": "血税",
    "Blood Witch": "鲜血巫婆",
    "Bloodfrenzy Feline": "血狂猫",
    "Bloodghast": "血妖",
    "Boggart Aether Zealot": "波尬乙太狂热者",
    "Boggart Assassin": "波尬刺客",
    "Boggart Void Mage": "波尬虚空法师",
    "Boggart": "波尬",
    "Bone Archer": "白骨弓箭手",
    "Bone Champion": "白骨斗士",
    "Bone Knight": "白骨骑士",
    "Bone Shambler Fragment": "白骨蹒跚碎片",
    "Bone Shambler Megalith": "白骨蹒跚巨石",
    "Bone Shambler": "白骨蹒跚者",
    "Bone Spear": "白骨标枪",
    "Bone Swap": "白骨换位",
    "Bone Wizard": "白骨巫师",
    "Bow": "弓",
    "Box of Woe": "悲哀盒",
    "Brain Bite": "咬脑子",
    "Brain Fly Swarm": "脑蝇群",
    "Butterfly Demon": "蝴蝶恶魔",
    "Cacophony": "杂音",
    "Call Imps": "召唤小贵",
    "Cannon Blast": "大炮冲击",
    "Cannon": "大炮",
    "Carrion Channel": "腐肉引导",
    "Cauterize": "炙烤",
    "Centaur Druid": "半人马德鲁伊",
    "Centaur": "半人马",
    "Chaos Aura": "混沌光环",
    "Chaos Blast": "混沌冲击",
    "Chaos Bolt": "混沌箭",
    "Chaos Champion": "混沌斗士",
    "Chaos Chimera": "混沌奇美拉",
    "Chaos Fiend": "混沌恶鬼",
    "Chaos Hound": "混沌猎犬",
    "Chaos Imp": "混沌小鬼",
    "Chaos Knight": "混沌骑士",
    "Chaos Quill": "混沌笔毫",
    "Chaos Shards": "混沌碎片",
    "Chaos Spirit": "混沌灵魂",
    "Charge Body": "充能躯体",
    "Charge": "冲锋",
    "Charged Body": "充能的躯体",
    "Chronos, Titan Immortal": "不朽泰坦克罗诺斯",
    "Clay Golem": "黏土魔像",
    "Cockatrice": "鸡蛇",
    "Concussive Idol": "震荡雕像",
    "Conductivity": "导通",
    "Copper Fiend": "铜制恶鬼",
    "Copper Imp Swarm": "铜制小鬼群",
    "Copper Mantis": "铜制螳螂",
    "Copper Spider": "铜制蜘蛛",
    "Copper Spike Ball": "铜制钉球",
    "Corrupted Lamasu": "腐败的拉玛苏",
    "Crackleball": "裂响球",
    "Crackleburn": "裂响灼烧",
    "Crossbow": "十字弩",
    "Crucible of Pain": "痛苦坩埚",
    "Cultist Chosen": "教众精卫",
    "Cultist Necromancer": "教众死灵法师",
    "Cultist": "教众",
    "Curse of the Fickle": "薄幸诅咒",
    "Curse of the Foolish": "愚蠢诅咒",
    "Curse of the Idol": "雕像诅咒",
    "Curse of the Weak": "虚弱诅咒",
    "Cyclops": "独眼巨人",
    "Dark Ball": "黑暗球",
    "Dark Breath": "黑暗吐息",
    "Dark Priest": "黑暗牧师",
    "Dark Satyr": "黑暗萨特",
    "Dark Torment": "黑暗折磨者",
    "Dark Tormenting Mass": "黑暗折磨群",
    "Dark Tormentor": "黑暗折磨者",
    "Dark Winter Night": "黑暗冬夜",
    "Death Beam": "死亡射线",
    "Death Snake": "死亡之蛇",
    "Death Touch": "死亡之触",
    "Death": "死亡",
    "Deathball": "死亡箭",
    "Deathchill Chimera": "死寒奇美拉",
    "Deathchill Tormentor": "死寒折磨者",
    "Demon Sorcerer": "恶魔法术师",
    "Destruction": "摧毁",
    "Displacer Beast": "移位兽",
    "Displacer Broodmother": "移位巢母",
    "Dozadoka, Minotaur King": "牛头怪王多萨多卡",
    "Dracolich": "龙巫妖",
    "Drain Life": "汲取生命",
    "Dream Hag": "梦境魔女",
    "Duergar Dark Priest": "灰矮人黑暗牧师",
    "Duergar Executioner": "灰矮人刽子手",
    "Duergar Lizard Lord": "灰矮人蜥蜴领主",
    "Duergar": "灰矮人",
    "Duplicate": "复制",
    "Earth Troll Coppermancer": "大地巨魔铜匠",
    "Earth Troll Magmancer": "大地巨魔岩浆术士",
    "Earth Troll Priest": "大地巨魔牧师",
    "Earth Troll": "大地巨魔",
    "Efreet Juggernaut": "魔神主宰",
    "Efreet": "魔神",
    "Elder Dream Hag": "梦境老魔女",
    "Emerald Breath": "翡翠吐息",
    "Enchanter": "附魔师",
    "Energy Knight": "能量骑士",
    "Enlighten Serpent": "启蒙巨蛇",
    "Eoggi, Void Slime King": "虚空史莱姆王俄基",
    "Evil Faery": "邪恶仙灵",
    "Evil Spirit": "邪恶灵魂",
    "Eye Beam": "眼射光束",
    "Fae Queen": "仙灵女王",
    "Fae Queen's Guard": "仙灵女王的卫队",
    "Faery Arcanist": "仙灵奥术师",
    "Faewitch": "仙灵巫婆",
    "Fallen Angel": "堕落天使",
    "False Prophet": "冒牌先知",
    "Famine Gaze": "饥荒凝视",
    "Feathered Serpent": "覆羽巨蛇",
    "Fiery Tormenting Mass": "火热折磨群",
    "Find Rider": "寻找坐骑",
    "Fire Bolt": "火焰弹",
    "Fire Bomber": "火焰轰炸者",
    "Fire Breath": "火焰吐息",
    "Fire Cluster Bomber": "火焰炸弹簇",
    "Fire Fiend": "火焰恶鬼",
    "Fire Fly Swarm": "萤火虫群",
    "Fire Gargoyle Statue": "火焰石像鬼雕像",
    "Fire Gargoyle": "火焰石像鬼",
    "Fire Ghost": "火焰幽灵",
    "Fire Lich": "火焰巫妖",
    "Fire Lion": "火焰狮子",
    "Fire Lizard Belcher": "火焰喷射蜥蜴",
    "Fire Protection": "火焰保护",
    "Fire Seed": "火焰种子",
    "Fire Snake": "火焰之蛇",
    "Fire Spirit": "火焰灵魂",
    "Fire Spores": "火焰包子",
    "Fire Witch": "火焰巫婆",
    "Fire Wizard": "火焰巫师",
    "Fire Wyrm Broodmother": "火焰浮龙巢母",
    "Fire Wyrm Egg": "火焰浮龙蛋",
    "Fire Wyrm": "火焰浮龙",
    "Firestorm Imp": "火焰风暴小鬼",
    "Flame Aura": "烈焰光环",
    "Flame Bat": "烈焰蝙蝠",
    "Flame Charge": "烈焰冲锋",
    "Flame Spit": "烈焰喷吐",
    "Flame Toad": "烈焰蟾蜍",
    "Flaming Eyeball": "烈焰眼球",
    "Flappy, Bat King": "蝙蝠王飘飘",
    "Flash of Lightning": "电光一闪",
    "Fleshy Mass": "大肉团",
    "Floating Eyeball": "漂浮眼球",
    "Flud, Mind Maggot King": "心智蛆王弗洛德",
    "Fly Swarm": "苍蝇群",
    "Fly Trap": "苍蝇陷阱",
    "Freezing Bolt": "冰冻箭",
    "Frenzy Claw": "狂热爪击",
    "Frenzy Haunt": "狂热作祟",
    "Frog Hop": "蛙跳",
    "Frost": "霜冻",
    "Frostfire Mage": "霜火法师",
    "Frostfire Protection": "霜火保护",
    "Frosty Torment": "寒霜折磨",
    "Frosty Tormentor": "寒霜折磨者",
    "Furnace Aura": "熔炉光环",
    "Furnace Fiend": "熔炉恶鬼",
    "Furnace Hound": "熔炉猎犬",
    "Furnace Mantis": "熔炉螳螂",
    "Furnace Shards": "熔炉碎片",
    "Furnace Spider": "熔炉蜘蛛",
    "Gargoyle Statue": "石像鬼雕像",
    "Gargoyle": "石像鬼",
    "Gaze of Winter": "凛冬凝视",
    "Gazing Spike Ball": "凝视钉球",
    "Gdeit, Gnome King": "侏儒王基特",
    "Gemini Twin": "双生子",
    "Ghost Mantis": "幽灵螳螂",
    "Ghost Toad": "幽灵蟾蜍",
    "Ghost": "幽灵",
    "Ghostly Goatia": "幽灵浮羊头",
    "Ghostly Lamasu": "幽灵拉玛苏",
    "Ghostly Mass": "幽灵群",
    "Ghostly Spike Ball": "幽灵钉球",
    "Giant Bag Of Bugs": "巨型袋装虫子",
    "Giant Bag of Bugs": "巨型虫子口袋",
    "Giant Bat": "巨型蝙蝠",
    "Giant Boggart": "巨型波尬",
    "Giant Bone Knight": "巨型白骨骑士",
    "Giant Chaos Chimera": "巨型混沌奇美拉",
    "Giant Chaos Lion": "巨型混沌狮子",
    "Giant Chaos Snake": "巨型混沌之蛇",
    "Giant Dark Tormentor": "巨型黑暗折磨者",
    "Giant Death Snake": "巨型死亡之蛇",
    "Giant Deathchill Chimera": "巨型死寒奇美拉",
    "Giant Displacer Beast": "巨型移位兽",
    "Giant Fiery Tormentor": "巨型火热折磨者",
    "Giant Fire Bomber": "巨型火焰轰炸者",
    "Giant Fire Imp": "巨型火焰小鬼",
    "Giant Fire Lizard": "巨型火焰蜥蜴",
    "Giant Fire Snake": "巨型火焰之蛇",
    "Giant Fireball": "巨型火球",
    "Giant Flame Toad": "巨型烈焰蟾蜍",
    "Giant Flaming Skull": "巨型烈焰颅骨",
    "Giant Floating Skull": "巨型漂浮颅骨",
    "Giant Frosty Tormentor": "巨型寒霜折磨者",
    "Giant Gargoyle": "巨型石像鬼",
    "Giant Ghost": "巨型幽灵",
    "Giant Gnome": "巨型侏儒",
    "Giant Goatia": "巨型浮羊头",
    "Giant Goblin": "巨型哥布林",
    "Giant Golden Snake": "巨型黄金蛇",
    "Giant Green Gorgon": "巨型绿色蛇发妖",
    "Giant Green Mushboom": "巨型绿色爆菇",
    "Giant Grey Mushboom": "巨型灰色爆菇",
    "Giant Ice Lion": "巨型寒冰狮子",
    "Giant Ice Lizard": "巨型寒冰蜥蜴",
    "Giant Icy Tormentor": "巨型寒冰折磨者",
    "Giant Iron Imp": "巨型钢铁小鬼",
    "Giant Mantis": "巨型螳螂",
    "Giant Metal Mantis": "巨型金属螳螂",
    "Giant Mind Devourer": "巨型心智吞噬者",
    "Giant Mind Maggot": "巨型心智蛆虫",
    "Giant Polar Bear": "巨型北极熊",
    "Giant Raven": "巨型乌鸦",
    "Giant Red Lion": "巨型红色狮子",
    "Giant Satyr": "巨型萨特",
    "Giant Snake": "巨型蛇",
    "Giant Soul Jar": "巨型灵魂瓶",
    "Giant Spark Imp": "巨型电光小鬼",
    "Giant Spider Queen": "巨型蜘蛛女王",
    "Giant Spider": "巨型蜘蛛",
    "Giant Spike Beast": "巨型钉刺兽",
    "Giant Spore Beast": "巨型孢子兽",
    "Giant Star Lion": "巨型星光狮子",
    "Giant Starfire Chimera": "巨型星火奇美拉",
    "Giant Void Bomber": "巨型虚空轰炸者",
    "Giant Void Toad": "巨型虚空蟾蜍",
    "Giant Werewolf": "巨型狼人",
    "Giant Worm Ball": "巨型虫球",
    "Giant Yeti": "巨型雪怪",
    "Gilded Lamasu": "金毛拉玛苏",
    "Glass Butterfly": "玻璃蝴蝶",
    "Glass Cockatrice": "玻璃鸡蛇",
    "Glass Gas": "玻璃气体",
    "Glass Gaze": "玻璃凝视",
    "Glass Golem": "玻璃魔像",
    "Glass Master": "玻璃大师",
    "Glass Mushboom": "玻璃爆菇",
    "Glass Shard": "玻璃碎片",
    "Glass Troubler": "玻璃麻烦鬼",
    "Glassy Gaze": "玻璃凝视",
    "Gnome Druid": "侏儒德鲁伊",
    "Gnome": "侏儒",
    "Goatia Tablet": "浮羊头石板",
    "Goatia": "浮羊头",
    "Goblin Fire Demolitionist": "火焰爆破哥布林",
    "Goblin Siege Mechanic": "哥布林",
    "Goblin Void Demolitionist": "虚空爆破哥布林",
    "Goblin Wizard": "哥布林巫师",
    "Goblin": "哥布林",
    "Gold Golem": "黄金魔像",
    "Gold Hand": "黄金之手",
    "Golden Skull": "黄金颅骨",
    "Golem": "魔像",
    "Grant Sorcery": "赋能法术",
    "Greater Demonic Altar": "大型恶魔祭坛",
    "Greater Lamasu": "大型拉玛苏",
    "Greater Life Drain": "大型生命汲取",
    "Greater Spore Beast": "大型孢子兽",
    "Greater Vampire": "大型吸血鬼",
    "Green Gorgon Breath": "绿蛇发妖吐息",
    "Green Gorgon": "绿色蛇发妖",
    "Green Mushboom": "绿色爆菇",
    "Green Slime Cube": "绿色史莱姆块",
    "Green Slime": "绿色史莱姆",
    "Grey Gorgon Breath": "灰蛇发妖吐息",
    "Grey Gorgon": "灰色蛇发妖",
    "Grey Mushboom": "灰色爆菇",
    "Grow Slimes": "养史莱姆",
    "Grow Thorns": "种荆棘",
    "Hallowed Earth Elemental": "神圣大地元素",
    "Halloween": "万圣节",
    "Haunt": "作祟",
    "Haunted": "遭祟",
    "Haunter": "祟魂",
    "Hellfire": "地狱火",
    "Hibernate": "冬眠",
    "Holy Breath": "神圣吐息",
    "Horned Toad": "有角蟾蜍",
    "Horrid Braying": "恐怖鸣叫",
    "Hurl Frostfire": "投掷霜火",
    "Ice Age": "寒冰时代",
    "Ice Ball": "寒冰球",
    "Ice Breath": "寒冰吐息",
    "Ice Eye": "寒冰之眼",
    "Ice Faery": "寒冰仙灵",
    "Ice Gargoyle Statue": "寒冰石像鬼雕像",
    "Ice Gargoyle": "寒冰石像鬼",
    "Ice Lich": "寒冰巫妖",
    "Ice Lion": "寒冰狮子",
    "Ice Lizard Belcher": "寒冰喷射蜥蜴",
    "Ice Lizard": "寒冰蜥蜴",
    "Ice Slime Cube": "寒冰史莱姆块",
    "Ice Spores": "寒冰孢子",
    "Ice Witch": "寒冰巫婆",
    "Ice Wizard": "寒冰巫师",
    "Ice Wyrm Broodmother": "寒冰浮龙巢母",
    "Ice Wyrm Egg": "寒冰浮龙蛋",
    "Ice Wyrm": "寒冰浮龙",
    "Icy Metabolism": "寒冰代谢",
    "Icy Spriggan Bush": "寒冰斯皮肯丛",
    "Icy Spriggan": "寒冰斯皮肯",
    "Icy Tormenting Mass": "寒冰折磨群",
    "Idol of Clarity": "明晰雕像",
    "Idol of Fiery Vengeance": "火热复仇雕像",
    "Idol of Life": "生命雕像",
    "Idol of Sorcery": "法术雕像",
    "Idol of Undeath": "不死雕像",
    "Idol of Vampirism": "吸血鬼雕像",
    "Idol of the Fickle": "薄幸雕像",
    "Idol of the Foolish": "愚蠢雕像",
    "Idol of the Weak": "虚弱雕像",
    "Ignite Poison": "点燃毒性",
    "Imp Collector": "小鬼收集者",
    "Imp Fire": "小鬼火焰",
    "Imp Harvest": "小鬼收割",
    "Imp Shot": "小鬼射击",
    "Imp Spark": "小鬼电光",
    "Imp Tablet": "小鬼石板",
    "Imp": "小鬼收集者",
    "Infernal Fireball": "地狱火球",
    "Insanity Fiend": "疯狂恶鬼",
    "Insanity Hound": "疯狂猎犬",
    "Inside Shell": "缩壳",
    "Invoke Chaos": "混沌行事",
    "Iron Blessing": "钢铁支付",
    "Iron Fae Thorn": "钢铁仙灵荆棘",
    "Iron Fiend": "钢铁恶鬼",
    "Iron Flick": "钢铁轻弹",
    "Iron Gaze": "钢铁凝视",
    "Iron Gnome": "钢铁侏儒",
    "Iron Hand": "钢铁之手",
    "Iron Plating": "钢铁种植",
    "Iron Thorn Bolt": "钢铁荆棘箭",
    "Iron Troubler": "钢铁麻烦鬼",
    "Jack O' Lantern": "南瓜灯",
    "Jeweled Hand": "珠光之手",
    "Kobold Crossbowman": "狗头人弩手",
    "Kobold Longbowman": "狗头人长弓手",
    "Kobold Siege Mechanic": "狗头人攻城技师",
    "Kobold": "狗头人",
    "Koseidius, Storm King": "风暴王克塞迪斯",
    "Krilt, Fire Imp King": "火焰小鬼王柯瑞特",
    "Lamasu": "拉玛苏",
    "Lanky Goblin": "瘦长哥布林",
    "Large Ghost Worm Ball": "大型幽灵虫球",
    "Large Iron Worm Ball": "大型钢铁虫球",
    "Large Toxic Worm Ball": "大型毒性虫球",
    "Large Worm Ball": "大型虫球",
    "Lesser Demonic Altar": "小型恶魔祭坛",
    "Lich": "巫妖",
    "Life Drain Frenzy": "狂热汲取生命",
    "Life Drain": "生命汲取",
    "Life Siphon": "生命吸取",
    "Lightning Bug Swarm": "闪电虫群",
    "Lightning Dive": "闪电俯冲",
    "Lightning Eye": "闪电之眼",
    "Lightning Mantis": "闪电螳螂",
    "Lightning Master": "闪电大师",
    "Lightning Protection": "闪电保护",
    "Lightning Snake": "闪电之蛇",
    "Lightning Talons": "闪电之爪",
    "Living Scroll of Fireball": "火焰活体卷轴",
    "Living Scroll of Lightning": "闪电活体卷轴",
    "Long Armed Melee": "长距装甲近战",
    "Longbow": "长弓",
    "Lunge": "匍匐",
    "Magma Shell": "岩浆壳",
    "Mantis": "螳螂",
    "Masked Wizard": "蒙面巫师",
    "Mass Blindness": "群体致盲",
    "Mass Heal": "群体治疗",
    "Mass of Eyes": "眼团",
    "Massive Fire Drake": "巨型火焰巨龙",
    "Massive Gold Drake": "巨型黄金巨龙",
    "Massive Metal Mantis": "巨型金属螳螂",
    "Massive Phase Bolt": "巨型相位弹",
    "Massive Storm Drake": "巨型风暴巨龙",
    "Massive Void Drake": "巨型虚空巨龙",
    "Mechanomancer": "机械巫师",
    "Medusa": "美杜莎",
    "Medusa's Gaze": "美杜莎凝视",
    "Mega Gargoyle Statue": "巨型石像鬼雕像",
    "Mega Gargoyle": "巨型石像鬼",
    "Meilmanir, Aelf King": "精灵王梅玛尼",
    "Metal Mantis": "金属螳螂",
    "Metal Minotaur": "金属牛头怪",
    "Micrognome": "微型侏儒",
    "Mind Blast": "心智冲击",
    "Mind Devourer": "心智吞噬者",
    "Mind Drain": "心智汲取",
    "Mind Maggot Drone": "心智蛆虫机",
    "Mind Maggot Queen": "心智蛆后",
    "Mind Maggot": "心智蛆虫",
    "Mind Vampire": "心智吸血鬼",
    "Minos, The Golden Bull": "金牛米诺斯",
    "Minotaur Juggernaut": "牛头怪主宰",
    "Minotaur Magma Shaman": "牛头怪岩浆萨满",
    "Minotaur": "牛头怪",
    "Mordred": "莫德雷德",
    "Mordred's Gaze": "莫德雷德凝视",
    "Mordred's Touch": "莫德雷德之触",
    "Mountain Mage": "山岳法师",
    "Mushbloom": "蘑菇花",
    "Mushboom Burst": "爆菇爆发",
    "Necromancer": "死灵法师",
    "Necromechanomancery": "死灵机械术士",
    "Night Hag": "黑夜魔女",
    "Nightmare Spark": "梦魇电光",
    "Nightmare Turtle": "梦魇龟",
    "Nine the Cat": "猫猫阿九",
    "Odin, Aesir Immortal": "不朽亚萨奥丁",
    "Ogre Juggernaut": "食人魔主宰",
    "Ogre": "食人魔",
    "Old Blood Witch": "鲜血老巫婆",
    "Old Faewitch": "仙灵老巫婆",
    "Old Fire Witch": "火焰老巫婆",
    "Old Ice Witch": "寒冰老巫婆",
    "Old Witch": "老巫婆",
    "Orc Boar Rider": "半兽人野猪骑士",
    "Orc Boar": "半兽人野猪",
    "Orc Flame Zealot": "半兽人烈焰狂热者",
    "Orc Houndlord": "半兽人",
    "Orc Juggernaut": "半兽人主宰",
    "Orc Pyromancer": "半兽人烈焰术士",
    "Orc Wolf": "半兽人座狼",
    "Orc": "半兽人",
    "Ossuonobius, Bone King": "白骨王欧索诺布斯",
    "Pain": "痛苦",
    "Pakkatok, Kobold King": "狗头人王帕卡托克",
    "Pale Rider": "死亡之青骑士",
    "Palinar, Grey Mushboom King": "灰爆菇王帕利纳",
    "Peck": "啄击",
    "Phase Bolt": "相位弹",
    "Phoenix Fire": "凤凰火",
    "Phoenix Starfire": "凤凰星火",
    "Phoenix": "凤凰",
    "Pickle Soul": "葬送灵魂",
    "Pillar of Bones": "白骨之柱",
    "Pillar of Worms": "蠕虫之柱",
    "Planar Interposition": "时空干预",
    "Player": "玩家",
    "Pointy Poke": "尖刺",
    "Poison Breath": "毒性吐息",
    "Poison Puff": "毒性喷雾",
    "Poison Spit": "毒性喷吐",
    "Poison Stab": "毒性背刺",
    "Polar Bear Blizzard Shaman": "北极熊暴风雪萨满",
    "Polar Bear": "北极熊",
    "Possessed Green Gorgon": "着魔的绿蛇发妖",
    "Possessed Polar Bear": "着魔的北极熊",
    "Possessed Raven": "着魔的乌鸦",
    "Possessed Spike Beast": "着魔的钉刺兽",
    "Possessed Spore Beast": "着魔的孢子兽",
    "Possessed Werewolf": "着魔的狼人",
    "Possessed Wild Man": "着魔的野人",
    "Praggi, Red Slime King": "红色史莱姆王帕基",
    "Psychic Goblin": "精神哥布林",
    "Purple Hand": "紫色之手",
    "Pyrubo, Efreet King": "魔神王皮鲁博",
    "Rainbow Drake": "彩虹巨龙",
    "Raven Mage": "乌鸦法师",
    "Raven": "乌鸦",
    "Razor Beast": "剃刀兽",
    "Reaper": "死神",
    "Reconstitution": "重组",
    "Red Cyclops": "独眼红巨人",
    "Red Goblin": "红色哥布林",
    "Red Mushboom": "红色爆菇",
    "Red Rider": "战争之红骑士",
    "Red Slime Cube": "红色史莱姆块",
    "Red Slime": "红色史莱姆",
    "Redcap": "红帽客",
    "Refresh": "刷新",
    "Regrow": "再生",
    "Ride the Wind": "御风而行",
    "Rogath, Ogre King": "食人魔王洛嘉斯",
    "Rolling Spike Ball": "滚动钉球",
    "Rot Blast": "腐化冲击",
    "Rot Bolt": "腐化弹",
    "Rot Fiend": "腐化恶鬼",
    "Rumplerog, Horned Toad King": "有角蟾蜍王隆勒罗",
    "Satyr": "萨特",
    "Scribe Chaos Scrolls": "抄写混沌卷轴",
    "Short Sword": "短剑",
    "Shraggi, Green Slime King": "绿色史莱姆王刷基",
    "Slazephan, Serpent Philosopher": "蛇哲人斯拉泽潘",
    "Sleep Touch": "睡眠之触",
    "Slime Brewer": "史莱姆酿师",
    "Slime Drake": "史莱姆巨龙",
    "slime drakes": "史莱姆巨龙",
    "Slime Growth": "史莱姆再生",
    "Slime Shot": "史莱姆射击",
    "Slimesoul Idol": "史莱姆魂雕像",
    "Small Ghost Worm Ball": "小型幽灵虫球",
    "Small Iron Worm Ball": "小型钢铁虫球",
    "Small Toxic Worm Ball": "小型毒性虫球",
    "Small Worm Ball": "小型虫球",
    "Snake Bites": "蛇咬",
    "Snake": "蛇",
    "Solar Orb": "太阳球",
    "Sorrow": "悲伤",
    "Soul Jar": "灵魂瓶",
    "Soul Suck": "灵魂吮吸",
    "Spawn Flies": "孳生苍蝇",
    "Spider Bite": "蜘蛛咬",
    "Spike Beast Alpha": "钉刺兽头领",
    "Spike Beast": "钉刺兽",
    "Spikebeast Spikes": "钉子野兽尖钉",
    "Spikebolt": "尖钉弹",
    "Spiked Golem": "钉刺魔像",
    "Spirit Fire": "灵魂火焰",
    "Spirit Shield": "灵魂护盾",
    "Spirit Spark": "灵魂电光",
    "Spirit Strider": "灵魂行者",
    "Spit Worms": "喷吐蠕虫",
    "Splitting": "分裂",
    "Spore Beast Alpha": "孢子兽头领",
    "Spore Beast": "孢子兽",
    "Spore Man Ancient": "孢子先人",
    "Spore Puff": "孢子喷雾",
    "Spores": "孢子",
    "Spriggan Bush": "斯皮肯丛",
    "Spriggan": "斯皮肯",
    "Star Lion": "星光狮子",
    "Starfire Blast": "星火冲击",
    "Starfire Chimera": "星火奇美拉",
    "Starfire Pulse": "星火脉冲",
    "Starfire Sorcerer": "星火法术师",
    "Starfire Spirit": "星火灵魂",
    "Steel Arachnid Abombination": "钢铁蛛形憎恶",
    "Steel Goatia": "钢铁浮羊头",
    "Steel Spider Queen": "钢铁蜘蛛女王",
    "Steel Spider": "钢铁蜘蛛",
    "Stone Gaze": "石质凝视",
    "Stoneskin": "石化皮肤",
    "Storm Ball": "风暴弹",
    "Storm Blast": "风暴冲击",
    "Storm Bolt": "风暴箭",
    "Storm Breath": "风暴吐息",
    "Storm Champion": "风暴斗士",
    "Storm Fiend": "风暴恶鬼",
    "Storm Knight": "风暴骑士",
    "Storm Spirit": "风暴灵魂",
    "Storm Strike": "风暴打击",
    "Storm Troll Juggernaut": "风暴巨魔主宰",
    "Storm Troll Mystic": "风暴巨魔秘术",
    "Storm Troll": "风暴巨魔",
    "Strife Healing": "纷争治疗",
    "Strife": "纷争",
    "Suicide Explosion": "自杀爆炸",
    "Summon Baby Aether Spider": "召唤乙太蜘蛛宝宝",
    "Summon Baby Giant Spider": "召唤巨型蜘蛛宝宝",
    "Summon Baby Steel Spider": "召唤钢铁蜘蛛宝宝",
    "Summon Baby Troubler": "召唤麻烦鬼宝宝",
    "Summon Clay Hound": "召唤黏土猎犬",
    "Summon Frostfire Hydra": "召唤霜火多头龙",
    "Summon Void Mantises": "召唤虚空螳螂",
    "Summon Wolf": "召唤狼",
    "Swamp Queen": "沼泽皇后",
    "Swat Ally": "扑打友军",
    "Swat Enemy": "扑打敌人",
    "Tentacle": "触手",
    "The Dreamer": "梦者",
    "The Furnace": "熔炉",
    "The Mischief Maker": "戏弄大师",
    "Thorn Bolt": "荆棘弹",
    "Thorncurse": "荆棘诅咒",
    "Thrahn, Iron Imp King": "钢铁小鬼王瑟兰",
    "Throw Spear": "投掷标枪",
    "Throw boulder": "投掷巨石",
    "Thunderbone Shaman": "雷骨萨满",
    "Tide of Rot": "腐化之潮",
    "Tide of Sin": "罪恶之潮",
    "Time Keeper": "计时员",
    "Timestop": "时间停止",
    "Tiny Phase Bolt": "小巧相位弹",
    "Titan": "泰坦",
    "Toad Chaos Sorcerer": "蟾蜍混沌法师",
    "Toad Nightmare Sorcerer": "蟾蜍梦魇法师",
    "Tombstone": "墓碑",
    "Tongue Lash": "舌头冲击",
    "Torrent of Bats": "蝙蝠折磨",
    "Towering Bone Shambler": "雄力白骨蹒跚者",
    "Towering Toadbeast": "雄力蟾蜍兽",
    "Toxic Bat": "毒性蝙蝠",
    "Toxic Boggart": "毒性波尬",
    "Toxic Gaze": "毒性凝视",
    "Toxic Raven": "毒性乌鸦",
    "Toxic Spike Ball": "毒性钉球",
    "Toxic Spore Beast": "毒性钉刺兽",
    "Toxic Spriggan Bush": "毒性斯皮肯丛",
    "Toxic Spriggan": "毒性斯皮肯",
    "Trafflerabus, Boggart King": "波尬王",
    "Trample": "践踏",
    "Translocator": "换位大师",
    "Treant": "树人",
    "Troll Geomancer": "巨魔大地术士",
    "Troll": "巨魔",
    "Trolltaur": "牛头巨魔",
    "Troubler": "麻烦鬼",
    "Troubling Mass": "麻烦鬼群",
    "Tungsten Imp": "钨化小鬼",
    "Tungsten Spike Ball": "钨化钉球",
    "Twilight Knight": "暮光骑士",
    "Twilight Protection": "暮光保护",
    "Twilight Seer": "暮光先知",
    "Twisted Healing": "扭曲治疗",
    "Vampire Bat": "吸血鬼蝙蝠",
    "Vampire Count": "吸血鬼伯爵",
    "Vampire Eye": "吸血鬼之眼",
    "Vampire Necromancer": "吸血鬼死灵术士",
    "Vampire": "吸血鬼",
    "Vampiric Mist": "吸血迷雾",
    "Void Bolt": "虚空之箭",
    "Void Bomber": "虚空轰炸者",
    "Void Breath": "虚空吐息",
    "Void Champion": "虚空斗士",
    "Void Cluster Bomber": "虚空炸弹簇",
    "Void Eye": "虚空之眼",
    "Void Flick": "虚空轻弹",
    "Void Ghost": "虚空幽灵",
    "Void Imp": "虚空小鬼",
    "Void Knight": "虚空骑士",
    "Void Lick": "虚空舔舐",
    "Void Magus": "虚空占星师",
    "Void Mantis": "虚空螳螂",
    "Void Maw": "虚空饕餮",
    "Void Phoenix": "虚空凤凰",
    "Void Rift": "虚空裂隙",
    "Void Slime Cube": "虚空史莱姆块",
    "Void Tango": "虚空探戈",
    "Void Toad": "虚空蟾蜍",
    "Void Watcher": "虚空守卫",
    "Volcano Shell": "火山壳",
    "Volcano Turtle": "火山龟",
    "Vuldakot, Chaos King": "混沌王伏达科",
    "Wander": "漫步",
    "War Banner": "战旗",
    "Warp Ball": "跃迁球",
    "Warptouch": "跃迁之触",
    "Watcher": "守卫",
    "Wereraven": "鸦人",
    "Werewolf Alpha": "狼人头领",
    "Werewolf Shaman": "狼人萨满",
    "Werewolf": "狼人",
    "White Rider": "瘟疫之白骑士",
    "Wight Blade": "尸妖之剑",
    "Wight Bow": "尸妖之弓",
    "Wild Man": "野人",
    "Wild Satyr": "狂野萨特",
    "Witch": "巫婆",
    "Witchfreeze": "巫婆之冻",
    "Wrath Gaze": "愤怒凝视",
    "Xiaggi, Ice Slime King": "寒冰史莱姆夏基",
    "Xilet, Spark Imp King": "电花小鬼王西莱",
    "Yeti Shaman": "雪怪萨满",
    "Yeti": "雪怪",
    "Yggdrasil": "世界树",
    "Yiggoroth, Troll King": "巨魔王伊格洛斯",
    "Zahlgrahd, Satyr King": "萨特王扎尔嘉德",
    "Zex Ku, Void King": "虚空王泽库",
    # 其他
    "Acidified": "酸化",
    "Afterlife": "来世",
    "Alchemist": "炼金",
    "Angelic": "天使",
    "Black Sky": "黑天",
    "Bloodlust": "嗜血",
    "Bloodrage": "血怒",
    "Blue Sky": "蓝天",
    "Bomber": "轰炸者",
    "Bone Splinter": "骨片",
    "Boon": "祝福",
    "Bright": "光明",
    "Burning": "燃烧",
    "Butterfly Wing": "蝶翼",
    "Call Kingdom": "召唤王国",
    "Calling": "呼唤",
    "Cauterizing": "烧灼",
    "Chaos Relay": "混沌中继",
    "Charge attack": "冲锋攻击",
    "Charred Bone": "焦骨",
    "Chasm": "虚空",
    "Crackling": "爆响",
    "Cruel": "残忍",
    "Dagger": "匕首",
    "Dark Protection": "黑暗保护",
    "Death Explosion": "死亡爆炸",
    "Demonbane": "降魔",
    "Disintegration": "分解",
    "Dragon Heart": "龙心",
    "Electrified": "带电",
    "Elemental Eye": "元素之眼",
    "Elemental Harvest": "元素收割",
    "Energy": "能量",
    "Enervation": "虚脱",
    "Entropy": "增熵",
    "Enveloping": "封存",
    "Essence": "菁华",
    "Fae": "仙灵",
    "Farsight": "远见",
    "Fire Claw": "火爪",
    "Firefly": "萤火虫",
    "Firestorm": "火焰风暴",
    "Frost Faery": "霜灵",
    "Frostfire": "霜火",
    "Frozen Skull": "冻颅",
    "Furnace": "熔炉",
    "Glassed": "璃化",
    "Gold Skull": "金颅",
    "Grey Bone": "灰骨",
    "Grove": "树丛",
    "Haunting": "作祟",
    "Heal Ally": "治疗友军",
    "Healing Aura": "治疗光环",
    "Heavenstrike": "天击",
    "Holy Protection": "神圣保护",
    "Ice Claw": "冰爪",
    "Ice Protection": "寒冰保护",
    "Icy": "寒冰",
    "Leap attack": "跳跃攻击",
    "Life": "生命",
    "Melee": "近战",
    "Memory": "记忆",
    "Mystic": "秘术",
    "Nightmare": "梦魇",
    "Oaken": "橡木",
    "Otherworldly": "异界",
    "Passive Teleportation": "被动传送",
    "Petrify Armor": "石化护甲",
    "Propagation": "传播",
    "Protection": "保护",
    "Pull Attack": "拉动攻击",
    "Quakeport": "地震传送",
    "Range": "远程",
    "Ranged Attack": "远程攻击",
    "Razor": "剃刀",
    "Red Flame": "红焰",
    "Red Star": "红星",
    "Sandstone": "砂岩",
    "Searing": "灼热",
    "Shell": "硬壳",
    "Shield Allies": "盾卫友军",
    "Shield Ally": "盾卫友军",
    "Sniper": "狙击",
    "Sorcery Mirror": "法术镜像",
    "Sorcery Shield": "法术护盾",
    "Soulpower": "魂力",
    "Sphere": "领域",
    "Spider Web": "蛛网",
    "Stillness": "寂静",
    "Stoning": "石刑",
    "Storm Cloud": "闪电云",
    "Stormcharge": "暴能",
    "Sunlight": "日光",
    "Swamp Aura": "沼泽光环",
    "Sword": "短剑",
    "Teleport Attack": "传送攻击",
    "Thorns": "荆棘",
    "Thunder": "雷电",
    "Torment": "折磨",
    "Toxic Agony": "毒痛",
    "Troll Regeneration": "巨魔再生",
    "Tundra Bolt": "苔原箭",
    "Tundra": "苔原",
    "Unnamed Shrine": "无名神龛",
    "Vigor": "活力",
    "Warped": "跃迁",
    "White Candle": "白烛",
    "Wyrmbrood": "龙巢",
    "freeze": "冻结",
    "petrify": "石化",
    "shield": "护盾",
    "slimes": "史莱姆",
}
tag_dic = {
    "Fire": "F 火焰",
    "Lightning": "L 闪电",
    "Ice": "I 寒冰",
    "Nature": "N 自然",
    "Arcane": "A 奥术",
    "Dark": "D 黑暗",
    "Holy": "H 神圣",
    "Sorcery": "S 法术",
    "Conjuration": "C 召唤",
    "Enchantment": "E 附魔",
    "Word": "W 真言",
    "Orb": "B 法球",
    "Dragon": "R 巨龙",
    "Translocation": "T 移位",
    "Metallic": "M 金属",
    "Eye": "Y 视线",
    "Chaos": "O 混沌"
}
attr_dic = {
    "acidicy": "酸性",
    "aether_spiders": "乙太蜘蛛",
    "arcane": "奥术伤害命中",
    "arcane_casting": "奥术施法",
    "arcane_damage": "奥术伤害",
    "aura": "光环",
    "berserk_duration": "狂暴回合",
    "blood_hound": "鲜血猎犬",
    "bolt": "箭矢",
    "bonus": "增益",
    "breath_damage": "吐息伤害",
    "cascade_range": "倾泻射程",
    "center summon": "中心召唤物",
    "charges_regained": "充能获取",
    "check_cur_hp": "检查当前生命",
    "clay_hound": "黏土猎犬",
    "color": "颜色",
    "copies": "复制",
    "court": "宫廷",
    "damage type": "伤害类型",
    "damage": "伤害",
    "dark": "黑暗伤害命中",
    "dark_blink": "黑暗扑闪",
    "dark_casting": "黑暗施法",
    "dark_units": "黑暗单位",
    "demon_units": "恶魔单位",
    "dream": "梦境",
    "duration": "持续回合",
    "extra_damage": "额外伤害",
    "fire_damage": "火焰伤害",
    "fire_edge": "火焰边缘",
    "fire_gaze": "火焰凝视",
    "fire_vulnerability": "火焰易伤",
    "flame": "火焰",
    "flow_range": "喷发范围",
    "freeze_chance": "冻结几率",
    "freezing": "冰冻",
    "glassify": "璃化",
    "heal": "治疗",
    "heaven_strike": "天堂之击",
    "holy_vulnerability": "神圣易伤",
    "hound": "猎犬",
    "hp_bonus": "生命加成",
    "hp_threshold": "生命阈值",
    "ice_hound": "寒冰猎犬",
    "icicle_harvest": "冰锥收割",
    "leap_range": "跳跃范围",
    "lightning_blink": "闪电扑闪",
    "lives": "命",
    "lycanthropy": "狼人",
    "max_channel": "引导回合上限",
    "max_charges": "充能上限",
    "max_health_loss": "失去生命上限",
    "melt_walls": "熔化墙壁",
    "meteor_size": "陨石尺寸",
    "minion_attacks": "小兵攻击",
    "minion_damage": "小兵伤害",
    "minion_duration": "小兵持续回合",
    "minion_health": "小兵生命",
    "minion_physical_resist": "小兵物理抗性",
    "minion_range": "小兵射程",
    "minion_resists": "小兵抗性",
    "multiplier": "倍率",
    "nature_casting": "自然施法",
    "num_summons": "召唤数量",
    "num_targets": "目标数量",
    "orb_walk": "法球信步",
    "petrify_duration": "石化持续回合",
    "physical_damage": "物理伤害",
    "prison": "监狱",
    "pull_strength": "拉动距离",
    "radius": "半径",
    "raising": "复活",
    "range": "射程",
    "requires_los": "无需视线",
    "resist": "抗性",
    "resist_arcane": "奥术抗性",
    "resistance_debuff": "抗性减益",
    "resists": "抗性",
    "shield_burn": "护盾燃烧",
    "shield_cooldown": "护盾冷却回合",
    "shield_max": "护盾上限",
    "shield_steal": "护盾偷取",
    "shields": "护盾",
    "shot_cooldown": "射击回合间隔",
    "soulbattery": "灵魂充能",
    "species": "种族",
    "storm_power": "风暴之力",
    "strikechance": "劈中几率",
    "stun_duration": "击晕回合",
    "swarm": "虫群",
    "totem": "图腾",
    "variant": "变化",
    "void_teleport": "虚空传送",
    "whole_map": "全图光环",
    "wither": "枯萎",
    "wolf_pack": "群狼术",
}
attrc_dic = {
    "arcane": "次",
    "arcane_damage": "点",
    "berserk_duration": "个",
    "bonus": "点",
    "breath_damage": "点",
    "cascade_range": "格",
    "charges_regained": "点",
    "copies": "个",
    "damage": "点",
    "dark": "次",
    "duration": "个",
    "extra_damage": "点",
    "fire_damage": "点",
    "fire_edge": "层",
    "fire_vulnerability": "点",
    "flow_range": "格",
    "freeze_chance": "点",
    "freeze_duration": "个",
    "heal": "点",
    "holy_vulnerability": "点",
    "hp_bonus": "点",
    "hp_threshold": "点",
    "lives": "条",
    "max_channel": "个",
    "max_charges": "点",
    "max_health_loss": "点",
    "meteor_size": "点",
    "minion_attacks": "次",
    "minion_damage": "点",
    "minion_duration": "个",
    "minion_health": "点",
    "minion_physical_resist": "点",
    "minion_range": "格",
    "minion_resists": "点",
    "multiplier": "点",
    "num_summons": "个",
    "num_targets": "个",
    "petrify_duration": "个",
    "physical_damage": "点",
    "pull_strength": "格",
    "radius": "格",
    "range": "格",
    "resist": "点",
    "resist_arcane": "点",
    "resistance_debuff": "点",
    "resists": "点",
    "shield_burn": "点",
    "shield_cooldown": "个",
    "shield_max": "个",
    "shield_steal": "点",
    "shields": "点",
    "shot_cooldown": "个",
    "strikechance": "点",
    "stun_duration": "个",
}
