dic = {
    # 属性 大小写
    'arcane': '奥术',
    'Arcane': '奥术',
    'chaos': '混沌',
    'Chaos': '混沌',
    'Conjuration': '召唤',
    'conjuration': '召唤',
    'Dark': '黑暗',
    'dark': '黑暗',
    'dragon': '巨龙',
    'Dragon': '巨龙',
    'Enchantment': '附魔',
    'enchantment': '附魔',
    'Eye': '视线',
    'eye': '视线',
    'fire': '火焰',
    'Fire': '火焰',
    'holy': '神圣',
    'Holy': '神圣',
    'Ice': '寒冰',
    'ice': '寒冰',
    'Lightning': '闪电',
    'lightning': '闪电',
    'Metallic': '金属',
    'metallic': '金属',
    'Nature': '自然',
    'nature': '自然',
    'Orb': '法球',
    'orb': '法球',
    'sorcery': '法术',
    'Sorcery': '法术',
    'Translocation': '移位',
    'translocation': '移位',
    'Word': '真言',
    'word': '真言',
    # 其他 大小写
    'acid': '酸性',
    'Acid': '酸性',
    'Arrow': '箭矢',
    'arrow': '箭矢',
    'berserk': '狂暴',
    'Berserk': '狂暴',
    'blind': '致盲',
    'Blind': '致盲',
    'buff_apply': '施加增益',
    'Buff_Apply': '施加增益',
    'Construct': '造物',
    'construct': '造物',
    'damage': '伤害',
    'Damage': '伤害',
    'debuff_apply': '施加减益',
    'Debuff_Apply': '施加减益',
    'demon': '恶魔',
    'Demon': '恶魔',
    'Elemental': '元素',
    'elemental': '元素',
    'flying': '飞行',
    'Flying': '飞行',
    'frozen': '冻结',
    'Frozen': '冻结',
    'glass': '玻璃',
    'Glass': '玻璃',
    'Glassification': '璃化',
    'glassification': '璃化',
    'Glassified': '璃化',
    'glassified': '璃化',
    'heal': '治疗',
    'Heal': '治疗',
    'Leap': '跳跃',
    'leap': '跳跃',
    'Living': '活物',
    'living': '活物',
    'max charges': '充能上限',
    'Max Charges': '充能上限',
    'Petrification': '石化',
    'petrification': '石化',
    'petrified': '石化',
    'Petrified': '石化',
    'Physical': '物理',
    'physical': '物理',
    'Poison': '毒性',
    'poison': '毒性',
    'Poisoned': '中毒',
    'poisoned': '中毒',
    'Radius': '半径',
    'radius': '半径',
    'Shield_Apply': '施加护盾',
    'shield_apply': '施加护盾',
    'Shield_Expire': '护盾期满',
    'shield_expire': '护盾期满',
    'Slime': '史莱姆',
    'slime': '史莱姆',
    'Sound_Effect': '音效',
    'sound_effect': '音效',
    'spider': '蜘蛛',
    'Spider': '蜘蛛',
    'Stun': '击晕',
    'stun': '击晕',
    'Stunned': '击晕',
    'stunned': '击晕',
    'Tongue': '石头',
    'tongue': '石头',
    'Undead': '不死',
    'undead': '不死',
    # 混用
    'Range': '远程',
    'Melee': '近战',
    'shield': '护盾',
    'petrify': '石化',
    'freeze': '冻结',
    # 玩家咒语
    'Aether Swap': '以太换位',
    'Annihilate': '歼灭术',
    'Arc Lightning': '弧状闪电',
    'Ball Lightning': '闪电法球',
    'Basilisk Armor': '蜥怪盔甲',
    'Blazerip': '熔刃术',
    'Blinding Light': '眩目之光',
    'Blink': '扑闪术',
    'Blizzard': '暴风雪',
    'Blue Lion': '蓝色狮子',
    'Boiling Blood': '热血术',
    'Bone Barrage': '白骨弹幕',
    'Call Archon': '召唤统领',
    'Call Seraph': '召唤炽天使',
    'Cantrip Cascade': '小招倾泻',
    'Chain Lightning': '闪电链',
    'Chaos Barrage': '混沌箭雨',
    'Chill Wind': '寒风术',
    'Chimera Familiar': '奇美拉佣兽',
    'Choir of Angels': '天使合唱',
    'Combust Poison': '燃烧毒药',
    'Conductance': '电导术',
    'Conjure Memories': '唤起记忆',
    'Darkness': '黑暗术',
    'Death Bolt': '死亡之箭',
    'Death Chill': '死亡之寒',
    'Death Cleave': '死亡分裂',
    'Death Gaze': '死亡凝视',
    'Death Shock': '死亡冲击',
    'Devour Mind': '吞噬心智',
    'Disperse': '驱散术',
    'Dispersion Field': '扩散场',
    'Dominate': '支配术',
    'Dragon Roar': '巨龙咆哮',
    'Earthen Sentinel': '大地哨兵',
    'Earthquake': '地震术',
    'Essence Flux': '菁华异变',
    'Eye of Fire': '火焰之眼',
    'Eye of Ice': '寒冰之眼',
    'Eye of Lightning': '闪电之眼',
    'Eye of Rage': '愤怒之眼',
    'Fae Court': '仙灵宫廷',
    'Fan of Flames': '扇状烈焰',
    'Fiery Tormentor': '火热折磨者',
    'Fire Drake': '火焰巨龙',
    'Fireball': '火球术',
    'Flame Burst': '炎爆术',
    'Flame Gate': '火门术',
    'Floating Eye': '漂浮之眼',
    'Flock of Eagles': '召唤鹰群',
    'Freeze': '冰冻术',
    'Frostfire Hydra': '霜火九头龙',
    'Ghostball': '幽灵球',
    'Giant Bear': '巨熊',
    'Glass Orb': '玻璃法球',
    'Gold Drake': '黄金巨龙',
    'Healing Light': '治愈之光',
    "Heaven's Wrath": '天堂之怒',
    'Heavenly Blast': '天堂冲击',
    'Heavenly Idol': '天堂雕像',
    'Hollow Flesh': '空心肉体',
    'Holy Armor': '圣甲术',
    'Holy Fire': '圣火术',
    'Hungry Maw': '饥肠怪',
    'Ice Drake': '寒冰巨龙',
    'Ice Orb': '寒冰法球',
    'Ice Phoenix': '寒冰凤凰',
    'Ice Vortex': '寒冰旋涡',
    'Iceball': '冰球术',
    'Icicle': '冰锥术',
    'Imp Swarm': '小鬼群',
    'Invoke Savagery': '野蛮行事',
    'Ironize': '讽刺术',
    'Knightly Oath': '骑士誓言',
    'Lightning Bolt': '闪电箭',
    'Lightning Form': '闪电形态',
    'Lightning Halo': '闪电光环',
    'Lightning Spire': '闪电尖塔',
    'Lightning Storm': '闪电风暴',
    'Magic Missile': '魔法飞弹',
    'Magnetize': '磁化术',
    'Mega Annihilate': '超级歼灭术',
    'Melt': '熔化术',
    'Mercurize': '汞化术',
    'Meteor Shower': '陨石雨',
    'Multicast': '多重施法',
    'Mystic Memory': '神秘记忆',
    'Mystic Power': '神秘力量',
    'Mystic Vision': '神秘视觉',
    'Nightmare Aura': '梦魇光环',
    'Orb Control': '法球控制',
    'Pain Mirror': '痛苦之镜',
    'Permanence': '持久术',
    'Petrification Aura': '石化光环',
    'Petrify': '石化术',
    'Pillar of Fire': '火柱术',
    'Plague of Filth': '污秽瘟疫',
    'Poison Sting': '毒刺术',
    'Prison of Thorns': '荆棘监狱',
    'Purity': '纯净术',
    'Pyrostatic Curse': '电焰诅咒',
    'Pyrostatic Pulse': '电焰脉冲',
    'Regeneration Aura': '再生光环',
    'Ring of Spiders': '蜘蛛之环',
    'Seal Fate': '封印命运',
    'Searing Orb': '灼热法球',
    'Searing Seal': '灼热封印',
    'Shrapnel Blast': '弹片冲击',
    'Siege Golems': '攻城魔像',
    'Sight of Blood': '鲜血视线',
    'Silver Spear': '银色标枪',
    'Siphon Shields': '虹吸护罩',
    'Slime Form': '史莱姆形态',
    'Soul Swap': '灵魂换位',
    'Soul Tax': '灵魂税',
    'Spider Queen': '蜘蛛女王',
    'Spikeball Factory': '钉球工厂',
    'Storm Burst': '风暴爆发',
    'Storm Drake': '风暴巨龙',
    'Suspend Mortality': '暂缓死亡',
    'Teleport': '传送术',
    'The Restless Dead': '不息的死者',
    'Thunder Strike': '雷击术',
    'Touch of Death': '死亡之触',
    'Toxic Spores': '有毒孢子',
    'Toxin Burst': '毒素爆发',
    'Twilight Gaze': '暮光凝视',
    'Underworld Passage': '冥界通道',
    'Void Beam': '虚空光束',
    'Void Drake': '虚空巨龙',
    'Void Orb': '虚空法球',
    'Volcanic Eruption': '火山爆发',
    'Wall of Ice': '寒冰之墙',
    'Watcher Form': '守卫形态',
    'Wheel of Death': '死亡之轮',
    'Wolf': '召狼术',
    'Word of Beauty': '美丽真言',
    'Word of Chaos': '混沌真言',
    'Word of Ice': '寒冰真言',
    'Word of Madness': '疯狂真言',
    'Word of Undeath': '不死真言',
    # 玩家咒语派生
    'Acidicy': '酸性',
    'Acidity': '酸性',
    'Aether Queen': '乙太女王',
    'Aether Spiders': '乙太蜘蛛',
    'Amplified Poison': '增效毒性',
    'Amplify Venom': '增效毒液',
    'Angelic Singer': '天使歌手',
    'Arcane Annihilation': '奥术歼灭',
    'Arcane Casting': '奥术施法',
    'Arcane Gaze': '奥术凝视',
    'Arcane Insulation': '奥术隔离',
    'Arcane Mimicry': '奥术模仿',
    'Arcane Taxation': '奥术税',
    'Archon Lightning': '统领闪电',
    'Armored Bear': '装甲巨熊',
    'Ash Ball': '灰烬球',
    'Aura': '光环',
    'Beauty': '美丽',
    'Berserk Duration': '狂暴回合',
    'Blindcasting': '蔽目施法',
    'Blood Bear': '鲜血巨熊',
    'Blood Hound': '鲜血狼',
    'Blood Lust': '嗜血术',
    'Bolt': '箭矢',
    'Bone Spears': '白骨长矛',
    'Bonus': '增益',
    'Bound Knight': '骑士效忠',
    'Breath Damage': '吐息伤害',
    'Bright Flame': '明炎术',
    'Brute Force': '蛮力',
    'Cascade Range': '倾泻射程',
    'Cascade': '倾泻歼灭',
    'Center Summon': '中心召唤物',
    'Channeling': '引导箭',
    'Chaos Ball': '混沌球',
    'Chaos Court': '混沌宫廷',
    'Check Cur Hp': '检查当前生命',
    'Claw': '爪击',
    'Clay Hound': '黏土猎犬',
    'Cloud Armor': '云甲术',
    'Cloud Conductance': '导电云',
    'Cloudform': '云形态',
    'Color': '颜色',
    'Copies': '复制',
    'Copper Imp': '铜质小鬼',
    'Copper Spikeballs': '铜制钉球',
    'Corrosion': '腐蚀性',
    'Court': '宫廷',
    'Culling': '宰割',
    'Cursed Bones': '受诅白骨',
    'Damage Bonus': '伤害增益',
    'Damage Type': '伤害类型',
    'Dark Annihilation': '黑暗歼灭',
    'Dark Blink': '黑暗扑闪',
    'Dark Casting': '黑暗施法',
    'Dark Dream': '黑暗梦境',
    'Dark Fury': '黑暗愤怒',
    'Dark Mimicry': '黑暗模仿',
    'Dark Swarm': '黑暗群',
    'Dark Units': '黑暗单位',
    'Death Roulette': '死亡轮盘',
    'Demon Frenzy': '恶魔狂热',
    'Demon Units': '恶魔单位',
    'Dire Wolf': '恐狼',
    'Disruption Bolt': '干扰弹',
    'Dive Attack': '俯冲攻击',
    'Dive': '俯冲',
    'Dragon Mage': '巨龙法师',
    'Drake Swap': '巨龙换位',
    'Dream': '梦境',
    'Duration': '持续回合',
    'Eagle': '鹰',
    'Earth Elemental': '大地元素',
    'Earthquake Totem': '地震图腾',
    'Echo Flash': '回响闪烁',
    'Echo Heal': '回响治疗',
    'Electric Dream': '电气梦境',
    'Elemental Spirits': '元素灵魂',
    'Energy Ball': '能量球',
    'Energy Bolt': '能量箭',
    'Essence Aura': '菁华光环',
    'Essence Drake': '菁华巨龙',
    'Extra Bolts': '额外箭矢',
    'Extra Damage': '额外伤害',
    'Fever Dream': '狂热梦境',
    'Fire Blast': '火焰冲击',
    'Fire Elemental': '火元素',
    'Fire Gaze': '火焰凝视',
    'Fire Imp': '火焰小鬼',
    'Fire Lizard': '火蜥蜴',
    'Fire Slime': '火焰史莱姆',
    'Fire Stone': '火石',
    'Fire Stones': '火石',
    'Fire Vulnerability': '火焰易伤',
    'Flame Rift': '火焰裂隙',
    'Flame Tongue': '火焰吐息',
    'Flame': '火焰',
    'Flametouch': '烈焰之触',
    'Flaming Arc': '弧状火焰',
    'Flaming Sword': '火焰剑',
    'Forced Transfer': '强制转移',
    'Freeze Chance': '冻结几率',
    'Freeze Duration': '冻结持续',
    'Freezing': '冰冻',
    'Frenzy Bite': '狂热撕咬',
    'Frostfire Tormentor': '霜火折磨者',
    'Furnace Imp': '熔炉小鬼',
    'Ghost King': '幽灵国王',
    'Ghost Mass': '幽灵群',
    'Ghostfire Tormentor': '鬼火折磨者',
    'Giant Imp': '巨型小鬼',
    'Giant Strength': '巨人之力',
    'Glass Faery': '玻璃仙灵',
    'Glass Mushbooms': '玻璃爆菇',
    'Glassification Bolt': '璃化弹',
    'glassify': '璃化',
    'Glassify': '璃化术',
    'Global': '全局',
    'Gluttony': '饕餮',
    'Golden Crusade': '黄金圣战',
    'Golem Siege Mechanic': '攻城魔像技师',
    'Good Faery': '好仙灵',
    'Grey Mushbooms': '灰色爆菇',
    'Gust of Wind': '劲风吹袭',
    'Heal Aura': '治疗光环',
    'Heaven Strike': '天堂之击',
    'Holy Bolt': '神圣弹',
    'Holy Fire Aura': '圣火光环',
    'Holy Fury': '神圣愤怒',
    'Holy Totem': '神圣图腾',
    'Holy Vulnerability': '神圣易伤',
    'Hound': '猎犬',
    'Hp Bonus': '生命加成',
    'HP Threshold': '生命阈值',
    'Hp Threshold': '生命阈值',
    'Ice Crush': '寒冰压溃',
    'Ice elemental': '寒冰元素',
    'Ice Hound': '寒冰猎犬',
    'Ice Penetration': '熔透寒冰',
    'Ice Slime': '寒冰史莱姆',
    'Icicle Harvest': '冰锥收割',
    'Icy Prison': '冰棘监狱',
    'Icy Thorn': '冰棘植物',
    'Inferno Cannon': '地狱火炮',
    'Infinite Cascades': '无限倾泻',
    'Insanity Imp': '疯狂小鬼',
    'Intensity': '强度',
    'Ioid Imp': '虚空小鬼',
    'Iron Imp': '钢铁小鬼',
    'Iron Prison': '铁棘监狱',
    'Iron Thorn': '铁棘植物',
    'Judgement Bolt': '审判箭',
    'Junk Golem': '废料魔像',
    'Leap Range': '跳跃范围',
    'Lightning Blink': '闪电扑闪',
    'Lightning Shield': '闪电护盾',
    'Magnetic Pulse': '磁性脉冲',
    'Magnetized Shards': '磁化碎片',
    'Manufactory': '制造大厂',
    'Matter Melting': '物质熔化',
    'Max Channel': '引导回合上限',
    'Max Health Loss': '失去生命上限',
    'Mega Swarm': '超级群',
    'Melting Flame': '熔炎术',
    'Mercurial Vengeance': '中汞复仇',
    'Mercurized': '中汞毒',
    'Metal Swarm': '金属群',
    'Meteor Size': '陨石尺寸',
    'Minion Attacks': '小兵攻击',
    'Minion Damage': '小兵伤害',
    'Minion Duration': '小兵持续回合',
    'Minion Health': '小兵生命',
    'Minion Physical Resist': '小兵物理抗性',
    'Minion Range': '小兵射程',
    'Minion Resists': '小兵抗性',
    'Moonblade': '月刃',
    'Morbidity': '发病率',
    'More Shrapnel': '更多弹片',
    'Multicopy': '再多一份',
    'Multiplier': '倍率',
    'Nature Casting': '自然施法',
    'Nature Mimicry': '自然模仿',
    'Num Summons': '召唤数量',
    'Num Targets': '目标数量',
    'orbs': '法球',
    'Orbs': '法球',
    'Petrify Duration': '石化持续',
    'Poison Bite': '毒性撕咬',
    'Poison Skin': '毒性皮肤',
    'Pounce': '猛扑',
    'Prison': '监狱',
    'Pull Distance': '拉动距离',
    'Puncturing Blast': '穿刺爆破',
    'Raising': '复活',
    'Red Dwarf': '红矮星',
    'Red Mushbooms': '红色爆菇',
    'Reincarnations': '复活',
    'Requires Los': '无需视线',
    'Resist': '抗性',
    'Resistance Debuff': '抗性减益',
    'Resistance Penetration': '抗性渗透',
    'Resistances': '抗性',
    'Resists': '抗性',
    'Rot Imp': '腐烂小鬼',
    'Safety': '安全',
    'Seal of Searing': '灼热封印',
    'Seraph': '炽天使',
    'Serpent Plague': '巨蛇瘟疫',
    'Shambler Assembly': '蹒跚集结',
    'Shield Burn': '护盾燃烧',
    'Shield': '护盾',
    'Shielding Light': '护盾之光',
    'Shielding': '护盾',
    'Shields': '护盾',
    'Shot Cooldown': '射击回合间隔',
    'Sing': '歌唱',
    'Slaughter Bolt': '屠杀弹',
    'Soul Battery': '灵魂充能',
    'Soulbattery': '灵魂充能',
    'Spark Imp': '电光小鬼',
    'Spark Spirit': '电光灵魂',
    'Spark': '电光',
    'Species': '种族',
    'Spirit Bind': '灵魂绑定',
    'Spirit Eater': '噬魂',
    'Spread Poison': '传播毒性',
    'Spreading Curse': '传播诅咒',
    'Spreading Flame': '挥炎术',
    'Steel Queen': '钢铁女王',
    'Stinging Totem': '毒刺图腾',
    'Storm Court': '风暴宫廷',
    'Storm Power': '风暴之力',
    'Stun Duration': '击晕回合',
    'Summon Queen': '召唤女王',
    'Swarm': '虫群',
    'Thorny Plant': '荆棘植物',
    'Thunder Stone': '雷石',
    'Thunder Stones': '雷石',
    'Thunderbird': '雷鸟',
    'Thunderbirds': '雷鸟',
    'Totem': '图腾',
    'Touch of the Raven': '乌鸦之触',
    'Touch of the Reaper': '死神之触',
    'Touch of the Vampire': '吸血鬼之触',
    'Toxic Fumes': '毒雾',
    'Trample Attack': '践踏攻击',
    'Universal Magnetism': '通用磁性',
    'Vampiric Gaze': '吸血鬼凝视',
    'Variant': '变化',
    'Venom Bear': '毒液巨熊',
    'Venom Beast': '毒液野兽',
    'Venom Drinker': '毒液饮者',
    'Vision Aura': '视觉光环',
    'Void Court': '虚空宫廷',
    'Void Slime': '虚空史莱姆',
    'Void Spawning': '虚空孳生',
    'Void Teleport': '虚空传送术',
    'Void Walk': '虚空漫步',
    'Voidtouch': '虚空之触',
    'Volcano': '火山术',
    'Wall Penetration': '墙壁渗透',
    'Weave Sorcery': '编织法术',
    'Wither': '枯萎',
    'Withering': '枯萎',
    'Wolf Pack': '群狼术',
    'Wrathtouch': '愤怒之触',
    'Zap': '劈中',
    # 玩家被动
    'Acid Fumes': '酸雾',
    'Arcane Accounting': '奥术节能',
    'Arcane Combustion': '奥术燃烧',
    'Arcane Shield': '奥术护盾',
    'Arch Conjurer': '大造物师',
    'Arch Enchanter': '大附魔师',
    'Arch Sorcerer': '大法术师',
    'Bone Guard': '白骨卫士',
    'Chaos Buddies': '混沌伙伴',
    'Chaos Casting': '混沌施法',
    'Chastisement': '惩戒',
    'Collected Agony': '收集痛苦',
    'Cracklevoid': '噼里啪啦',
    'Crystal Power': '水晶之力',
    'Dark Lord': '黑暗领主',
    'Dragon Lord': '巨龙领主',
    'Faestone': '仙灵石',
    'Fiery Judgement': '炽热审判',
    'Fire Lord': '火焰领主',
    'Frostbite': '冻伤',
    'Frozen Fragility': '冻脆',
    'Ghostfire': '鬼火',
    'Glittering Dance': '闪光之舞',
    'Hibernation': '休眠',
    'Holy Thunder': '神圣雷霆',
    'Holy Water': '圣水',
    'Horror': '恐怖',
    'Houndlord': '猎犬领主',
    'Hungry Dead': '饿死鬼',
    'Hypocrisy': '虚伪',
    'Ice Lord': '寒冰领主',
    'Ice Tap': '寒冰塔',
    'Icy Vengeance': '寒冰复仇',
    'Inferno Engine': '地狱火引擎',
    'Inferno Engines': '地狱火引擎',
    'Last Word': '遗言',
    'Light Lord': '光明领主',
    'Lightning Frenzy': '闪电狂潮',
    'Lightning Warp': '闪电扭曲',
    'Megavenom': '超级毒液',
    'Melting Armor': '熔化盔甲',
    'Metal Lord': '金属领主',
    'Minion Regeneration': '小兵再生',
    'Moonspeaker': '月语者',
    'Natural Vigour': '自然活力',
    'Nature Lord': '自然领主',
    'Necrostatics': '尸毒学',
    'Orb Lord': '法球领主',
    'Paralyzing Venom': '麻痹毒液',
    'Prince of Ruin': '毁灭王子',
    'Purestrike': '纯粹打击',
    'Pyrophilia': '嗜热症',
    'Radiant Chill': '寒气逼人',
    'Righteous March': '正义进军',
    'Scalespinner': '龙鳞旋抗',
    'Searing Heat': '灼热',
    'Shatter Shards': '破碎飞片',
    'Shielded Minions': '带盾小兵',
    'Shock Value': '冲击价值',
    'Silkshifter': '织丝者',
    'Soul Harvest': '灵魂收割',
    'Spider Spawning': '蜘蛛孳生',
    'Starfire': '星星之火',
    'Steam Anima': '蒸汽灵魂',
    'Storm Caller': '风暴召师',
    'Thorn Garden': '荆棘花园',
    'Thunder Lord': '雷霆领主',
    'Translocation Master': '转移大师',
    'Unblinking Eye': '定睛之眼',
    'Unholy Alliance': '不洁联盟',
    'Venom Spit': '毒液喷吐',
    'Void Lord': '虚空领主',
    'Void Spikes': '虚空尖塔',
    'Voidflame Lantern': '虚空火灯',
    'White Flame': '白色火焰',
    # 玩家被动派生
    'Rock Collection': '岩石收藏',
    'Hunger': '饥饿',
    'Burning Ghost': '燃烧的幽灵',
    'Fae Thorn': '仙灵荆棘',
    'Fae Stone': '仙灵石',
    'Hell Hound': '地狱猎犬',
    'Spin Web': '织蛛网',
    'Steam Elemental': '蒸汽元素',
    'Starcharged': '星光充能',
    'Pyrostatics': '电焰',
    'Natural Healing': '自然治疗',
    'Lycanthrophy': '狼人',
    # 物品
    'Aether Dagger': '以太匕首',
    'Bag of Bags': '一袋袋子',
    'Bag of Spikes': '一袋钉子',
    'Chaos Bell': '混沌之铃',
    'Death Dice': '死亡骰子',
    'Dragon Horn': '巨龙号角',
    'Draught of Memories': '记忆药剂',
    'Earth Troll Crown': '大地巨魔之冠',
    'Earthquake Orb': '地震法球',
    'Elixir of Youth': '不老琼浆',
    'Energy Shield': '能量护盾',
    'Golden Stopwatch': '黄金秒表',
    'Healing Potion': '治疗药水',
    'Mana Potion': '魔法药水',
    'Memory Enhancement': '记忆增强',
    'Oculus': '天眼',
    'Orb of Corruption': '腐败法球',
    'Portal Disruptor': '传送门干扰器',
    'Portal Key': '传送门钥匙',
    'Shrine Disruptor': '神龛扰乱器',
    'Stone Shield': '石质护盾',
    'Storm Troll Crown': '风暴巨魔之冠',
    'Teleporter': '传送器',
    'Troll Crown': '巨魔之冠',
    'Youth': '永葆青春',
    # 关卡物品
    'Unnamed spell': '无名咒语',
    'Unnamed Item': '无名物品',
    'Unnamed buff': '无名增益',
    # 'Channeling': '引导中',
    'Immobilized': '固定',
    'Siege Machine': '攻城机器',
    'Clarity': '明晰',
    'Running Away': '逃跑',
    'Unnamed': '无名',
    'Tile': '地块',
    'Rift': '裂隙',
    'Heal Dot': '治愈点',
    'Memory Orb': '记忆球',
    'Spell Recharge': '咒语充能',
    'Ruby Heart': '红宝心',
    'Gold': '黄金',
    'Arcane Circle': '奥术之环',
    'Chaos Circle': '混沌之环',
    'Conjuration Circle': '召唤之环',
    'Dark Circle': '黑暗之环',
    'Dragon Circle': '巨龙之环',
    'Enchantment Circle': '附魔之环',
    'Eye Circle': '视线之环',
    'Fire Circle': '火焰之环',
    'Holy Circle': '神圣之环',
    'Ice Circle': '寒冰之环',
    'Lightning Circle': '闪电之环',
    'Metallic Circle': '金属之环',
    'Nature Circle': '自然之环',
    'Orb Circle': '法球之环',
    'Sorcery Circle': '法术之环',
    'Translocation Circle': '移位之环',
    'Word Circle': '真言之环',
    'Shop': '商店',
    'Gate': '大门',
    # 怪物
    "Aelf Lightning Artist": "精灵闪电艺术家",
    "Aelf": "精灵",
    "Aesir": "亚萨",
    "Aether Charge": "乙太冲锋",
    "Aether Spider": "乙太蜘蛛",
    "Arcane Blast": "乙太冲击",
    "Ash Bolt": "灰烬箭",
    "Ash Fiend": "灰烬恶鬼",
    "Ash Imp": "灰烬小鬼",
    "Assemble Bone Knight": "组装白骨骑士",
    "Bag of Bugs": "一袋虫子",
    "Bat": "蝙蝠",
    "Blizzard Beast": "暴风雪野兽",
    "Blood Witch": "鲜血巫婆",
    "Bloodghast": "血妖",
    "Boggart": "波尬",
    "Bone Knight": "白骨骑士",
    "Bone Shambler Fragment": "白骨蹒跚碎片",
    "Bone Shambler Megalith": "白骨蹒跚巨石",
    "Bone Shambler": "白骨蹒跚者",
    "Bone Swap": "白骨换位",
    "Bone Wizard": "白骨巫师",
    "Bow": "弓",
    "Butterfly Demon": "蝴蝶恶魔",
    "Centaur": "半人马",
    "Chaos Chimera": "混沌奇美拉",
    "Chaos Fiend": "混沌恶鬼",
    "Chaos Imp": "混沌小鬼",
    "Chaos Knight": "混沌骑士",
    "Chaos Shards": "混沌碎片",
    "Charge": "冲锋",
    "Cockatrice": "鸡蛇",
    "Copper Fiend": "铜制恶鬼",
    "Copper Spike Ball": "铜制钉球",
    "Crossbow": "十字弩",
    "Cultist": "教众",
    "Cyclops": "独眼巨人",
    "Dark Tormentor": "黑暗折磨者",
    "Death Beam": "死亡射线",
    "Death Snake": "死亡之蛇",
    "Deathchill Chimera": "死寒奇美拉",
    "Displacer Beast": "移位野兽",
    "Displacer Broodmother": "移位巢母",
    "Dracolich": "龙巫妖",
    "Drain Life": "汲取生命",
    "Dream Hag": "梦境魔女",
    "Duergar": "垛格",
    "Earth Troll": "大地巨魔",
    "Efreet": "魔神",
    "Energy Knight": "能量骑士",
    "Evil Faery": "邪恶仙境",
    "Fae Queen": "仙灵女王",
    "Faery Arcanist": "仙境奥术师",
    "False Prophet": "冒牌先知",
    "Fire Bolt": "火焰弹",
    "Fire Bomber": "火焰轰炸者",
    "Fire Fiend": "火焰恶鬼",
    "Fire Ghost": "火焰幽灵",
    "Fire Lion": "火焰狮子",
    "Fire Seed": "火焰种子",
    "Fire Snake": "火焰蛇",
    "Fire Spirit": "火焰灵魂",
    "Fire Witch": "火焰巫婆",
    "Fire Wyrm Egg": "火焰浮龙蛋",
    "Fire Wyrm": "火焰浮龙",
    "Flame Toad": "烈焰蟾蜍",
    "Flaming Eyeball": "烈焰眼球",
    "Fleshy Mass": "大肉团",
    "Floating Eyeball": "漂浮眼球",
    "Fly Swarm": "苍蝇群",
    "Frenzy Claw": "狂热爪击",
    "Frenzy Haunt": "狂热作祟",
    "Frost": "霜冻",
    "Frosty Tormentor": "寒霜折磨者",
    "Furnace Fiend": "熔炉恶鬼",
    "Furnace Shards": "熔炉碎片",
    "Gargoyle Statue": "石像鬼雕像",
    "Gargoyle": "石像鬼",
    "Gaze of Winter": "凛冬凝视",
    "Ghost": "幽灵",
    "Ghostly Mass": "幽灵群",
    "Giant Fire Imp": "巨型火焰小鬼",
    "Giant Fireball": "巨型火球",
    "Giant Flaming Skull": "巨型烈焰颅骨",
    "Giant Floating Skull": "巨型漂浮颅骨",
    "Giant Iron Imp": "巨型钢铁小鬼",
    "Giant Spark Imp": "巨型电光小鬼",
    "Giant Spider": "巨型蜘蛛",
    "Giant Worm Ball": "巨型虫球",
    "Glass Butterfly": "玻璃蝴蝶",
    "Glass Cockatrice": "玻璃鸡蛇",
    "Glass Gas": "玻璃气体",
    "Glass Golem": "玻璃魔像",
    "Glass Mushboom": "玻璃爆菇",
    "Gnome": "侏儒",
    "Goatia": "浮羊头",
    "Goblin": "哥布林",
    "Golden Skull": "黄金颅骨",
    "Golem": "魔像",
    "Greater Life Drain": "大型生命汲取",
    "Greater Spore Beast": "大型孢子野兽",
    "Greater Vampire": "大型吸血鬼",
    "Green Gorgon": "绿色蛇发妖",
    "Green Mushboom": "绿色爆菇",
    "Green Slime": "绿色史莱姆",
    "Grey Gorgon": "灰色蛇发妖",
    "Grey Mushboom": "灰色爆菇",
    "Horned Toad": "有角蟾蜍",
    "Ice Lion": "寒冰狮子",
    "Ice Lizard": "寒冰蜥蜴",
    "Ice Wyrm Egg": "寒冰浮龙蛋",
    "Ice Wyrm": "寒冰浮龙",
    "Icy Spriggan Bush": "寒冰斯皮肯丛",
    "Icy Spriggan": "寒冰斯皮肯",
    "Infernal Fireball": "地狱火球",
    "Insanity Fiend": "疯狂恶鬼",
    "Iron Fiend": "钢铁恶鬼",
    "Iron Gaze": "钢铁凝视",
    "Kobold": "狗头人",
    "Lamasu": "拉玛苏",
    "Large Worm Ball": "大型虫球",
    "Lich": "巫妖",
    "Lightning Dive": "闪电俯冲",
    "Lightning Snake": "闪电蛇",
    "Lightning Talons": "闪电之爪",
    "Living Scroll of Fireball": "火焰活体卷轴",
    "Living Scroll of Lightning": "闪电活体卷轴",
    "Mantis": "螳螂",
    "Mass of Eyes": "眼团",
    "Metal Mantis": "金属螳螂",
    "Mind Devourer": "心智吞噬者",
    "Mind Drain": "心智汲取",
    "Mind Maggot Queen": "心智蛆后",
    "Mind Maggot": "心智蛆虫",
    "Mind Vampire": "心智吸血鬼",
    "Minotaur": "牛头怪",
    "Mordred": "莫德雷德",
    "Mordred's Gaze": "莫德雷德凝视",
    "Mordred's Touch": "莫德雷德之触",
    "Mushbloom": "蘑菇花",
    "Night Hag": "黑夜魔女",
    "Nightmare Turtle": "梦魇龟",
    "Ogre": "食人魔",
    "Old Blood Witch": "鲜血老巫婆",
    "Old Witch": "老巫婆",
    "Orc Pyromancer": "半兽人烈焰术士",
    "Orc Wolf": "半兽人座狼",
    "Orc": "半兽人",
    "Peck": "啄击",
    "Phoenix": "凤凰",
    "Poison Puff": "毒性喷雾",
    "Polar Bear": "北极熊",
    "Purple Hand": "紫色之手",
    "Raven Mage": "乌鸦法师",
    "Raven": "乌鸦",
    "Reaper": "死神",
    "Red Mushboom": "红色爆菇",
    "Red Slime": "红色史莱姆",
    "Redcap": "红帽客",
    "Ride the Wind": "御风而行",
    "Rolling Spike Ball": "滚动钉球",
    "Rot Blast": "腐化冲击",
    "Rot Bolt": "腐化弹",
    "Rot Fiend": "腐化恶鬼",
    "Satyr": "羊蹄人",
    "Short Sword": "短剑",
    "Small Worm Ball": "小型虫球",
    "Snake": "蛇",
    "Spike Beast": "钉子野兽",
    "Spikebolt": "尖钉弹",
    "Spit Worms": "喷吐蠕虫",
    "Spore Beast": "孢子野兽",
    "Spore Puff": "孢子喷雾",
    "Spriggan Bush": "斯皮肯丛",
    "Spriggan": "斯皮肯",
    "Star Lion": "星光狮子",
    "Starfire Chimera": "星火奇美拉",
    "Steel Spider": "钢铁蜘蛛",
    "Storm Fiend": "风暴恶鬼",
    "Storm Knight": "风暴骑士",
    "Storm Strike": "风暴打击",
    "Storm Troll": "风暴巨魔",
    "Swamp Queen": "沼泽皇后",
    "Tentacle": "触手",
    "Thorn Bolt": "荆棘弹",
    "Throw boulder": "投掷巨石",
    "Throw Spear": "投掷标枪",
    "Titan": "泰坦",
    "Towering Bone Shambler": "雄力白骨蹒跚者",
    "Towering Toadbeast": "雄力蟾蜍兽",
    "Toxic Gaze": "毒性凝视",
    "Trample": "践踏",
    "Treant": "树人",
    "Troll": "巨魔",
    "Troubler": "麻烦鬼",
    "Tungsten Imp": "钨化小鬼",
    "Twilight Knight": "暮光骑士",
    "Vampire Bat": "吸血鬼蝙蝠",
    "Vampire Eye": "吸血鬼之眼",
    "Vampire": "吸血鬼",
    "Vampiric Mist": "吸血迷雾",
    "Void Bomber": "虚空轰炸者",
    "Void Flick": "虚空轻弹",
    "Void Imp": "虚空小鬼",
    "Void Knight": "虚空骑士",
    "Void Rift": "虚空裂隙",
    "Void Toad": "虚空蟾蜍",
    "Volcano Turtle": "火山龟",
    "Werewolf": "狼人",
    "Wild Man": "野人",
    "Witch": "巫婆",
    "Wrath Gaze": "愤怒凝视",
    "Yeti": "雪怪",
    # 稀有怪物
    "Arachnid Wizard": "蛛形巫师",
    "Army of Hades": "哈迪斯大军",
    "Arrow of Flame": "烈焰之箭",
    "Arrow of Halting": "定身之箭",
    "Arrow of Poison": "毒性之箭",
    "Aura of Clarity": "明晰光环",
    "Aura of Life": "生命光环",
    "Aura of Undeath": "不死光环",
    "Aura of Woe": "悲哀光环",
    "Avian Wizard": "鸟形巫师",
    "Awaken Bone Shamblers": "白骨蹒跚醒转者",
    "Ball of Starfire": "星火球",
    "Bat Dragon": "蝙蝠巨龙",
    "Beasts of Earth": "大地野兽",
    "Beckon Dragons": "召唤巨龙",
    "Black Rider": "黑色骑士",
    "Bone Spear": "白骨标枪",
    "Box of Woe": "悲哀盒",
    "Cacophony": "杂音",
    "Call Imps": "召唤小贵",
    "Carrion Channel": "腐肉引导",
    "Chaos Aura": "混沌光环",
    "Chaos Quill": "混沌笔毫",
    "Chronos, Titan Immortal": "不朽泰坦·克罗诺斯",
    "Concussive Idol": "震荡雕像",
    "Conductivity": "导通",
    "Crucible of Pain": "痛苦坩埚",
    "Curse of the Idol": "雕像诅咒",
    "Dark Ball": "黑暗球",
    "Dark Breath": "黑暗吐息",
    "Dark Priest": "黑暗牧师",
    "Dark Winter Night": "黑暗冬夜",
    "Death": "死亡",
    "Demon Sorcerer": "恶魔法术师",
    "Destruction": "摧毁",
    "Duplicate": "复制",
    "Emerald Breath": "翡翠吐息",
    "Enchanter": "附魔师",
    "Fae Queen's Guard": "仙灵女王的卫队",
    "Fallen Angel": "堕落天使",
    "Famine Gaze": "饥荒凝视",
    "Feathered Serpent": "覆羽巨蛇",
    "Fire Breath": "火焰吐息",
    "Fire Lich": "火焰巫妖",
    "Fire Protection": "火焰保护",
    "Fire Spores": "火焰包子",
    "Fire Wizard": "火焰巫师",
    "Flash of Lightning": "电光一闪",
    "Fly Trap": "苍蝇陷阱",
    "Frog Hop": "蛙跳",
    "Frostfire Mage": "霜火法师",
    "Frostfire Protection": "霜火保护",
    "Gemini Twin": "双身子",
    "Giant Soul Jar": "巨型灵魂瓶",
    "Glass Master": "玻璃大师",
    "Glass Shard": "玻璃碎片",
    "Glassy Gaze": "玻璃凝视",
    "Goblin Wizard": "哥布林巫师",
    "Grant Sorcery": "赋能法术",
    "Green Gorgon Breath": "绿蛇发妖吐息",
    "Grey Gorgon Breath": "灰蛇发妖吐息",
    "Grow Thorns": "召唤经济",
    "Halloween": "万圣节",
    "Haunt": "作祟",
    "Hellfire": "地狱火",
    "Hibernate": "冬眠",
    "Holy Breath": "神圣吐息",
    "Horrid Braying": "恐怖鸣叫",
    "Hurl Frostfire": "投掷霜火",
    "Ice Age": "寒冰时代",
    "Ice Ball": "寒冰球",
    "Ice Breath": "寒冰吐息",
    "Ice Lich": "寒冰巫妖",
    "Ice Spores": "寒冰孢子",
    "Ice Wizard": "寒冰巫师",
    "Icy Metabolism": "寒冰代谢",
    "Idol of Clarity": "明晰雕像",
    "Idol of Fiery Vengeance": "火热复仇雕像",
    "Idol of Life": "生命雕像",
    "Idol of Sorcery": "法术雕像",
    "Idol of Undeath": "不死雕像",
    "Idol of Vampirism": "吸血鬼雕像",
    "Ignite Poison": "点燃毒性",
    "Imp Collector": "小鬼收集者",
    "Imp Harvest": "小鬼收割",
    "Inside Shell": "缩壳",
    "Invoke Chaos": "混沌行事",
    "Iron Blessing": "钢铁支付",
    "Iron Plating": "钢铁种植",
    "Jack O' Lantern": "南瓜灯",
    "Life Drain": "生命汲取",
    "Life Siphon": "生命吸取",
    "Lightning Master": "闪电大师",
    "Lightning Protection": "闪电保护",
    "Masked Wizard": "蒙面巫师",
    "Mass Blindness": "群体致盲",
    "Mass Heal": "群体治疗",
    "Mechanomancer": "机械巫师",
    "Medusa": "美杜莎",
    "Medusa's Gaze": "美杜莎凝视",
    "Minos, The Golden Bull": "金牛·米诺斯",
    "Mountain Mage": "山岳法师",
    "Mushboom Burst": "爆菇爆发",
    "Necromancer": "死灵法师",
    "Necromechanomancery": "死灵机械术士",
    "Nightmare Spark": "梦魇电光",
    "Odin, Aesir Immortal": "不朽亚萨·奥丁",
    "Pain": "痛苦",
    "Pale Rider": "苍白骑士",
    "Phase Bolt": "相位弹",
    "Phoenix Fire": "凤凰火",
    "Phoenix Starfire": "凤凰星火",
    "Pickle Soul": "葬送灵魂",
    "Pillar of Bones": "白骨之柱",
    "Pillar of Worms": "蠕虫之柱",
    "Planar Interposition": "时空干预",
    "Poison Breath": "毒性吐息",
    "Rainbow Drake": "彩虹巨龙",
    "Reconstitution": "重组",
    "Red Cyclops": "独眼红巨人",
    "Red Rider": "红色骑士",
    "Refresh": "刷新",
    "Regrow": "再生",
    "Scribe Chaos Scrolls": "抄写混沌卷轴",
    "Slime Drake": "史莱姆巨龙",
    "Slime Growth": "史莱姆再生",
    "Slimesoul Idol": "史莱姆魂雕像",
    "Snake Bites": "蛇咬",
    "Solar Orb": "太阳球",
    "Sorrow": "悲伤",
    "Soul Jar": "灵魂瓶",
    "Spawn Flies": "孳生苍蝇",
    "Spider Bite": "蜘蛛咬",
    "Spikebeast Spikes": "钉子野兽尖钉",
    "Splitting": "分裂",
    "Spore Man Ancient": "孢子先人",
    "Spores": "孢子",
    "Starfire Pulse": "星火脉冲",
    "Starfire Sorcerer": "星火法术师",
    "Stone Gaze": "石质凝视",
    "Stoneskin": "石化皮肤",
    "Storm Ball": "风暴弹",
    "Storm Bolt": "风暴箭",
    "Storm Breath": "风暴吐息",
    "Strife Healing": "纷争治疗",
    "Strife": "纷争",
    "Summon Clay Hound": "召唤黏土猎犬",
    "Summon Frostfire Hydra": "召唤霜火九头龙",
    "Summon Wolf": "召唤狼",
    "Swat Ally": "扑打友军",
    "Swat Enemy": "扑打敌人",
    "The Dreamer": "梦者",
    "The Furnace": "熔炉",
    "The Mischief Maker": "戏弄大师",
    "Thorncurse": "荆棘诅咒",
    "Tide of Rot": "腐化之潮",
    "Tide of Sin": "罪恶之潮",
    "Time Keeper": "计时员",
    "Timestop": "时间停止",
    "Tombstone": "墓碑",
    "Torrent of Bats": "蝙蝠折磨",
    "Translocator": "换位大师",
    "Troll Geomancer": "巨魔大地术士",
    "Twilight Protection": "暮光保护",
    "Twilight Seer": "暮光先知",
    "Twisted Healing": "扭曲治疗",
    "Void Breath": "虚空吐息",
    "Void Magus": "虚空占星师",
    "Void Maw": "虚空饕餮",
    "Void Phoenix": "虚空凤凰",
    "Void Tango": "虚空探戈",
    "Void Watcher": "虚空守卫",
    "Volcano Shell": "火山壳",
    "Wander": "漫步",
    "War Banner": "战旗",
    "Warp Ball": "跃迁球",
    "Warptouch": "跃迁之触",
    "Watcher": "守卫",
    "White Rider": "白色骑士",
    "Yggdrasil": "世界树",
    # 变体
    # "Acrinar, Green Mushboom King": "",
    # "Aelf Aethermancer": "",
    # "Aelf Arachnomancer": "",
    # "Aelf Elite": "",
    # "Aelf Siege Engineer": "",
    # "Aether Arachnid Abombination": "",
    # "Aether Prism": "",
    # "Arachnid Abombination": "",
    # "Armored Goblin": "装甲哥布林",
    # "Armored Satyr": "装甲羊蹄人",
    # "Axe": "斧子",
    # "Baby Troubler": "",
    # "Bag of Brain Flies": "",
    # "Bag of Fire Flies": "",
    # "Bag of Lightning Bugs": "",
    # "Ballista": "",
    # "Big Troubler": "",
    # "Blackblaze Shaman": "",
    # "Blackfire Aura": "",
    # "Blinding Powder": "",
    # "Blood Tax": "",
    # "Bloodfrenzy Feline": "",
    # "Boggart Aether Zealot": "",
    # "Boggart Assassin": "",
    # "Boggart Void Mage": "",
    # "Bone Archer": "",
    # "Bone Champion": "",
    # "Brain Fly Swarm": "",
    # "Cannon Blast": "",
    # "Cannon": "",
    # "Cauterize": "",
    # "Centaur Druid": "",
    # "Chaos Blast": "",
    # "Chaos Bolt": "",
    # "Chaos Hound": "",
    # "Chaos Spirit": "",
    # "Charge Body": "",
    # "Charged Body": "",
    # "Clay Golem": "",
    # "Copper Imp Swarm": "",
    # "Copper Mantis": "",
    # "Copper Spider": "",
    # "Corrupted Lamasu": "",
    # "Crackleball": "",
    # "Crackleburn": "",
    # "Cultist Chosen": "",
    # "Cultist Necromancer": "",
    # "Dark Satyr": "",
    # "Dark Torment": "",
    # "Dark Tormenting Mass": "",
    # "Deathball": "",
    # "Deathchill Tormentor": "",
    # "Duergar Dark Priest": "",
    # "Duergar Executioner": "",
    # "Duergar Lizard Lord": "",
    # "Earth Troll Coppermancer": "",
    # "Earth Troll Magmancer": "",
    # "Earth Troll Priest": "",
    # "Efreet Juggernaut": "",
    # "Elder Dream Hag": "",
    # "Enlighten Serpent": "",
    # "Eye Beam": "",
    # "Faewitch": "",
    # "Fiery Tormenting Mass": "",
    # "Find Rider": "",
    # "Fire Cluster Bomber": "",
    # "Fire Fly Swarm": "",
    # "Fire Gargoyle Statue": "",
    # "Fire Gargoyle": "",
    # "Fire Wyrm Broodmother": "",
    # "Firestorm Imp": "",
    # "Flame Aura": "",
    # "Flame Bat": "",
    # "Flame Charge": "",
    # "Flame Spit": "",
    # "Flappy, Bat King": "",
    # "Flud, Mind Maggot King": "",
    # "Freezing Bolt": "",
    # "Frosty Torment": "",
    # "Furnace Aura": "",
    # "Furnace Hound": "",
    # "Furnace Mantis": "",
    # "Furnace Spider": "",
    # "Gazing Spike Ball": "",
    # "Ghost Mantis": "",
    # "Ghost Toad": "",
    # "Ghostly Goatia": "",
    # "Ghostly Lamasu": "",
    # "Ghostly Spike Ball": "",
    # "Giant Bat": "",
    # "Giant Boggart": "",
    # "Giant Chaos Lion": "",
    # "Giant Chaos Snake": "",
    # "Giant Death Snake": "",
    # "Giant Displacer Beast": "",
    # "Giant Fire Bomber": "",
    # "Giant Fire Snake": "",
    # "Giant Ghost": "",
    # "Giant Green Mushboom": "",
    # "Giant Grey Mushboom": "",
    # "Giant Ice Lion": "",
    # "Giant Mantis": "",
    # "Giant Mind Maggot": "",
    # "Giant Polar Bear": "",
    # "Giant Satyr": "",
    # "Giant Snake": "",
    # "Giant Star Lion": "",
    # "Giant Void Bomber": "",
    # "Gilded Lamasu": "",
    # "Glass Gaze": "",
    # "Glass Troubler": "",
    # "Gnome Druid": "",
    # "Goblin Fire Demolitionist": "",
    # "Goblin Siege Mechanic": "",
    # "Goblin Void Demolitionist": "",
    # "Gold Golem": "",
    # "Gold Hand": "",
    # "Greater Demonic Altar": "",
    # "Greater Lamasu": "",
    # "Grow Slimes": "",
    # "Hallowed Earth Elemental": "",
    # "Haunted": "",
    # "Haunter": "",
    # "Ice Eye": "",
    # "Ice Faery": "",
    # "Ice Gargoyle Statue": "",
    # "Ice Gargoyle": "",
    # "Ice Witch": "",
    # "Ice Wyrm Broodmother": "",
    # "Icy Tormenting Mass": "",
    # "Insanity Hound": "",
    # "Iron Fae Thorn": "",
    # "Iron Flick": "",
    # "Iron Gnome": "",
    # "Iron Hand": "",
    # "Iron Thorn Bolt": "",
    # "Iron Troubler": "",
    # "Jeweled Hand": "",
    # "Kobold Crossbowman": "",
    # "Kobold Longbowman": "",
    # "Kobold Siege Mechanic": "",
    # "Koseidius, Storm King": "",
    # "Krilt, Fire Imp King": "",
    # "Lanky Goblin": "",
    # "Large Ghost Worm Ball": "",
    # "Large Iron Worm Ball": "",
    # "Large Toxic Worm Ball": "",
    # "Lesser Demonic Altar": "",
    # "Lightning Bug Swarm": "",
    # "Lightning Mantis": "",
    # "Longbow": "",
    # "Lunge": "",
    # "Massive Metal Mantis": "",
    # "Massive Phase Bolt": "",
    # "Mega Gargoyle Statue": "",
    # "Mega Gargoyle": "",
    # "Metal Minotaur": "",
    # "Micrognome": "",
    # "Mind Blast": "",
    # "Mind Maggot Drone": "",
    # "Minotaur Juggernaut": "",
    # "Minotaur Magma Shaman": "",
    # "Nine the Cat": "",
    # "Ogre Juggernaut": "",
    # "Old Faewitch": "",
    # "Old Fire Witch": "",
    # "Old Ice Witch": "",
    # "Orc Boar Rider": "",
    # "Orc Boar": "",
    # "Orc Flame Zealot": "",
    # "Orc Houndlord": "",
    # "Orc Juggernaut": "",
    # "Ossuonobius, Bone King": "",
    # "Pakkatok, Kobold King": "",
    # "Palinar, Grey Mushboom King": "",
    # "Pointy Poke": "",
    # "Poison Spit": "",
    # "Poison Stab": "",
    # "Polar Bear Blizzard Shaman": "",
    # "Possessed Green Gorgon": "",
    # "Possessed Polar Bear": "",
    # "Possessed Raven": "",
    # "Possessed Spike Beast": "",
    # "Possessed Spore Beast": "",
    # "Possessed Werewolf": "",
    # "Possessed Wild Man": "",
    # "Psychic Goblin": "",
    # "Razor Beast": "",
    # "Red Goblin": "",
    # "Slazephan, Serpent Philosopher": "",
    # "Slime Brewer": "",
    # "Slime Shot": "",
    # "Small Ghost Worm Ball": "",
    # "Small Iron Worm Ball": "",
    # "Small Toxic Worm Ball": "",
    # "Soul Suck": "",
    # "Spike Beast Alpha": "",
    # "Spiked Golem": "",
    # "Spirit Shield": "",
    # "Spirit Strider": "",
    # "Spore Beast Alpha": "",
    # "Starfire Blast": "",
    # "Starfire Spirit": "",
    # "Steel Arachnid Abombination": "",
    # "Steel Goatia": "",
    # "Storm Blast": "",
    # "Storm Spirit": "",
    # "Storm Troll Juggernaut": "",
    # "Storm Troll Mystic": "",
    # "Summon Void Mantises": "",
    # "Thrahn, Iron Imp King": "",
    # "Thunderbone Shaman": "",
    # "Tiny Phase Bolt": "",
    # "Toad Chaos Sorcerer": "",
    # "Toad Nightmare Sorcerer": "",
    # "Toxic Bat": "",
    # "Toxic Boggart": "",
    # "Toxic Raven": "",
    # "Toxic Spike Ball": "",
    # "Toxic Spore Beast": "",
    # "Toxic Spriggan Bush": "",
    # "Toxic Spriggan": "",
    # "Trafflerabus, Boggart King": "",
    # "Trolltaur": "",
    # "Troubling Mass": "",
    # "Tungsten Spike Ball": "",
    # "Vampire Count": "",
    # "Vampire Necromancer": "",
    # "Void Cluster Bomber": "",
    # "Void Ghost": "",
    # "Void Mantis": "",
    # "Vuldakot, Chaos King": "",
    # "Wereraven": "",
    # "Werewolf Alpha": "",
    # "Werewolf Shaman": "",
    # "Wight Bow": "",
    # "Wild Satyr": "",
    # "Witchfreeze": "",
    # "Xilet, Spark Imp King": "",
    # "Yeti Shaman": "",
    # "Zahlgrahd, Satyr King": "",
    # "Zex Ku, Void King": "",
}
tag_dic = {
    'Fire': 'F 火焰',
    'Lightning': 'L 闪电',
    'Ice': 'I 寒冰',
    'Nature': 'N 自然',
    'Arcane': 'A 奥术',
    'Dark': 'D 黑暗',
    'Holy': 'H 神圣',
    'Sorcery': 'S 法术',
    'Conjuration': 'C 召唤',
    'Enchantment': 'E 附魔',
    'Word': 'W 真言',
    'Orb': 'B 法球',
    'Dragon': 'R 巨龙',
    'Translocation': 'T 移位',
    'Metallic': 'M 金属',
    'Eye': 'Y 视线',
    'Chaos': 'O 混沌'
}
attr_dic = {
    'acidicy': '酸性',
    'arcane': '奥术伤害命中',
    'arcane_casting': '奥术施法',
    'aura': '光环',
    'berserk_duration': '狂暴回合',
    'blood_hound': '鲜血猎犬',
    'bolt': '箭矢',
    'bonus': '增益',
    'breath_damage': '吐息伤害',
    'cascade_range': '倾泻射程',
    'center summon': '中心召唤物',
    'check_cur_hp': '检查当前生命',
    'clay_hound': '黏土猎犬',
    'color': '颜色',
    'copies': '复制',
    'court': '宫廷',
    'damage type': '伤害类型',
    'damage': '伤害',
    'dark': '黑暗伤害命中',
    'dark_blink': '黑暗扑闪',
    'dark_casting': '黑暗施法',
    'demon_units': '恶魔单位',
    'dream': '梦境',
    'duration': '持续回合',
    'extra_damage': '额外伤害',
    'fire_vulnerability': '火焰易伤',
    'flame': '火焰',
    'freezing': '冰冻',
    'glassify': '璃化',
    'heal': '治疗',
    'heaven_strike': '天堂之击',
    'holy_vulnerability': '神圣易伤',
    'hound': '猎犬',
    'hp_bonus': '生命加成',
    'hp_threshold': '生命阈值',
    'ice_hound': '寒冰猎犬',
    'icicle_harvest': '冰锥收割',
    'leap_range': '跳跃范围',
    'lightning_blink': '闪电扑闪',
    'lycanthrophy': '狼人',
    'max_channel': '引导回合上限',
    'max_charges': '充能上限',
    'max_health_loss': '失去生命上限',
    'meteor_size': '陨石尺寸',
    'minion_attacks': '小兵攻击',
    'minion_damage': '小兵伤害',
    'minion_duration': '小兵持续回合',
    'minion_health': '小兵生命',
    'minion_physical_resist': '小兵物理抗性',
    'minion_range': '小兵射程',
    'minion_resists': '小兵抗性',
    'multiplier': '倍率',
    'nature_casting': '自然施法',
    'num_summons': '召唤数量',
    'num_targets': '目标数量',
    'petrify_duration': '石化持续',
    'prison': '监狱',
    'radius': '半径',
    'raising': '复活',
    'range': '射程',
    'requires_los': '无需视线',
    'resist': '抗性',
    'resistance_debuff': '抗性减益',
    'resists': '抗性',
    'shield_burn': '护盾燃烧',
    'shields': '护盾',
    'shot_cooldown': '射击回合间隔',
    'soulbattery': '灵魂充能',
    'species': '种族',
    'storm_power': '风暴之力',
    'stun_duration': '击晕回合',
    'swarm': '虫群',
    'totem': '图腾',
    'variant': '变化',
    'void_teleport': '虚空传送数',
    'wither': '枯萎',
    'wolf_pack': '群狼术',
}
attrc_dic = {
    'arcane': '次',
    'berserk_duration': '个',
    'bonus': '点',
    'breath_damage': '点',
    'cascade_range': '格',
    'copies': '个',
    'damage': '点',
    'dark': '次',
    'duration': '个',
    'fire_vulnerability': '点',
    'heal': '点',
    'holy_vulnerability': '点',
    'hp_bonus': '点',
    'hp_threshold': '点',
    'max_channel': '个',
    'max_charges': '点',
    'meteor_size': '点',
    'minion_attacks': '次',
    'minion_damage': '点',
    'minion_duration': '个',
    'minion_health': '点',
    'minion_physical_resist': '点',
    'minion_range': '格',
    'minion_resists': '点',
    'multiplier': '点',
    'num_summons': '个',
    'num_targets': '个',
    'radius': '格',
    'range': '格',
    'resistance_debuff': '点',
    'shield_burn': '点',
    'shields': '点',
    'shot_cooldown': '个',
    'stun_duration': '个',
    'void_teleport': '个数',
}
